pytorch/tensordict

- .github/workflows/nightly_build.yml
Fixes refs in the nightly built workflow.
> [BugFix] Nightly build

- tensordict/memmap.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_memmap.py
- test/test_tensordict.py
Hopefully last sync with torchrl
> [Sync] Sync with torchrl

- tensordict/tensordict.py
- test/test_tensordict.py
Add a `set_default` method to the `TensorDictBase` class. This method aims at mimicking the behaviour of `setdefault` in `dict`
Add corresponding tests for `set_default`
close #7
> [Feature] Create a `TensorDict.set_default` method

- tensordict/tensordict.py
- test/test_tensordict.py
Solves the bug described [here](https://github.com/pytorch/rl/issues/652)
cc [raphajaner](https://github.com/raphajaner)
> [BugFix] Representation of nested tensordicts

- tensordict/tensordict.py
Makes the custom operation tensordict subclasses private.
> [Feature] Make custom ops tensordict classes private

- .github/workflows/wheels.yml
> [BugFix, CI] Fix py38 tag for python 3.8 wheels

- .github/workflows/wheels.yml
Edits the release workflow for v0.0.1a
> [Versioning] TensorDict v0.0.1a

- tensordict/tensordict.py
- test/test_tensordict.py
Implements the lazy stack tensordict indexing feature.
> [Feature] nested LazyStack indexing

- tensordict/tensordict.py
- test/test_tensordict.py
Fixes edge cases for tensordict.exclude
> [WIP, BugFix] Fix exclude

- tensordict/tensordict.py
Some tricks to improve performance of common operations
> [Feature] Faster construction

- tensordict/nn/common.py
- tensordict/nn/functional_modules.py
- tensordict/nn/probabilistic.py
- test/test_tensordictmodules.py
This is a WIP PR to fix the tests in #11
> [WIP] Fix tests for functional refactor

- tensordict/tensordict.py
- test/test_tensordict.py
Fixes memmap creation for nested TDs and tests the feature.
> [BugFix] Fix memmap creation for nested TDs

- tensordict/tensordict.py
- test/test_tensordict.py
Fixes the locking mechanism for nested tds
> [BugFix] Fix locking mechanism

- test/test_tensordict.py
Tests that cloning a locked td results in a non-locked td
> [Test] test that cloned locked TDs aren't locked

- README.md
- docs/source/index.rst
Adds a doc badge in the readme
> [Doc] Doc Badge

- tensordict/nn/common.py
- test/test_functorch.py
- test/test_tensordictmodules.py
Ensures that dependency on functoch is only optional for code and test execution
> [BugFix] Optional functorch dependency

- .circleci/config.yml
- .circleci/unittest/linux_torchrec/scripts/environment.yml
- .circleci/unittest/linux_torchrec/scripts/install.sh
- .circleci/unittest/linux_torchrec/scripts/post_process.sh
- .circleci/unittest/linux_torchrec/scripts/run-clang-format.py
- .circleci/unittest/linux_torchrec/scripts/run_test.sh
- .circleci/unittest/linux_torchrec/scripts/setup_env.sh
- .github/workflows/docs.yml
- README.md
- docs/source/index.rst
- setup.py
- tensordict/__init__.py
- tensordict/memmap.py
- tensordict/metatensor.py
- tensordict/nn/common.py
- tensordict/nn/distributions/continuous.py
- tensordict/nn/distributions/discrete.py
- tensordict/nn/functional_modules.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/_utils_internal.py
- test/test_functorch.py
- test/test_tensordict.py
- test/test_tensordictmodules.py
- test/test_torchrec.py
Bring branch `functional_refactor` up to date with main.
> Merge main into functional_refactor

- .circleci/unittest/linux/scripts/install.sh
- .circleci/unittest/linux/scripts/setup_env.sh
- .circleci/unittest/linux_stable/scripts/install.sh
- .circleci/unittest/linux_torchrec/scripts/install.sh
- .circleci/unittest/linux_torchrec/scripts/setup_env.sh
- .pre-commit-config.yaml
- setup.cfg
- tensordict/memmap.py
- tensordict/nn/functional_modules.py
- tensordict/tensordict.py
- test/test_memmap.py
- test/test_tensordict.py
- test/test_torchrec.py
Some more formatting for FBCode
> [Doc, Test] Some more formatting for FBCode

- .pre-commit-config.yaml
- pyproject.toml
- tensordict/metatensor.py
- tensordict/nn/common.py
- tensordict/nn/distributions/continuous.py
- tensordict/nn/distributions/truncated_normal.py
- tensordict/nn/functional_modules.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensordict.py
Final formatting for fbcode + update versions
> [Formatting] Final FBCode formatting

- README.md
- setup.py
Badges are cool
The nightly download is a total misrepresentation as some tests download it in torchrl, maybe we should not include it?
> [Doc] Some more badges

- .git-blame-ignore-revs
> [Formatting] ignore formatting commits

- tensordict/nn/functional_modules.py
Solves an issue with python function definition in loops where the loop variable is overwritten at each iteration in already defined functions.
More info: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> [BugFix] Mutable default arguments

- .pre-commit-config.yaml
- docs/source/conf.py
- setup.cfg
- tensordict/metatensor.py
- tensordict/nn/distributions/continuous.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/tensordict.py
- test/test_tensordict.py
> [Formatting] Minor formatting improvements

- tensordict/tensordict.py
> [Formatting] Fix expand

- tensordict/tensordict.py
Reverts pytorch-labs/tensordict#78
> Revert "[Formatting] Fix expand"

- tensordict/nn/sequence.py
Fix another occurrence of same issue as #81
> [BugFix] TensorDictSequential inheritance fix

- tensordict/nn/functional_modules.py
Some modules (specifically non-parametric ones) can be skipped in some cases with the current looping mechanism in swap-states.
There current fix solves that.
> [BugFix] Ensure that all modules are visited during module population

- benchmarks/pytree_benchmarks.py
- tensordict/tensordict.py
Adds a benchmark file and improves runtime of various common functions
> [Feature] Benchmarks

- README.md
- docs/source/overview.rst
This PR fixes `esemble` typo to `ensemble`.
Making documention better with less typos.
> docs: fix esemble -> ensemble typo

- benchmarks/distributed_benchmark.py
- docs/source/distributed.rst
- docs/source/index.rst
Adds an example of memmap tensor usage in distributed settings + doc
> [Doc] Distributed doc

- tensordict/prototype/tensorclass.py
- test/test_tensorclass.py
- test/test_tensorclass_nofuture.py
Adds support for tensorclass construction with unnamed args
> [Feature] Allow for tensorclass construction with unnamed args

- tensordict/tensordict.py
Avoids a set creation in select to speed up the execution
> [Refactor] Speedup select method

- tensordict/nn/probabilistic.py
- tensordict/tensordict.py
- test/test_tensordict.py
Fixing a couple of copy-pasted typos I noticed.
> [Typo] fist -> first

- tensordict/tensordict.py
- test/test_tensordict.py
I noticed that `items_meta` and `values_meta` were missing the `leaves_only` keyword that their analogues all expose. While adding it, I realised that the implementation of each of these methods was in fact broken in the `make_unset=False` case, since we were doing checks like `if isinstance(item, TensorDictBase)` where `item` is expected to be a `MetaTensor`. 
This PR both adds the missing kwargs and fixes the bug, and adds a test to check for the correct behaviour.
> [BugFix] Fix items_meta, values_meta

- benchmarks/common_ops.py
- tensordict/metatensor.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/_utils_internal.py
- test/test_tensordict.py
Speeds up various operations in TensorDict
> [Refactor] Various speed improvements

- .circleci/unittest/linux_torchrec/scripts/install.sh
Attempt to fix the torchrec CI branch failure
> [BugFix] TorchRec test failure

- tensordict/nn/functional_modules.py
Fixes wrongful functorch.vmap imports
> [BugFix] Fix functorch vmap imports

- tensordict/nn/functional_modules.py
- test/test_functorch.py
- test/test_tensordictmodules.py
Fixes some functorch broken imports
> [BugFix] Fix functorch imports

- test/test_functorch.py
Fix functorch tests that should be skipped when the lib is not installed
> [BugFix] Fix functorch test import

- tensordict/tensordict.py
Refactors the `torch.cat` operation when the destination is a regular tensordict
> [Refactor] torch.cat with destination td refactoring

- tensordict/tensordict.py
- test/test_tensordict.py
Fixes a device error in the `torch.cat` tests
> [BugFix] Fix test_cat device error

- tensordict/tensordict.py
- test/test_tensordict.py
> [BugFix] Fix LazyStackedTensorDict.update for LazyStackedTensorDict -> LazyStackedTensorDict

- README.md
Adds some more doc about tensorclass
> [Doc] Some more doc for tensorclass

- .circleci/config.yml
- .circleci/unittest/linux/scripts/environment.yml
- .circleci/unittest/linux/scripts/run_test.sh
- .circleci/unittest/linux_stable/scripts/environment.yml
- .circleci/unittest/linux_stable/scripts/run_test.sh
- .circleci/unittest/linux_torchrec/scripts/environment.yml
- .circleci/unittest/linux_torchrec/scripts/run_test.sh
This PR adds code coverage checks to the CI pipelines following the changes in pytorch/rl#533. 
I don't have permissions to complete the setup on codecov.io so this is blocked until that is resolved.
> [Feature] Add codecov checks

- docs/source/index.rst
- tutorials/sphinx_tuto/data_fashion.py
- tutorials/sphinx_tuto/tensorclass_fashion.py
Some formatting fixes + tensorclass tutorial for `tutorials` branch.
> [Docs] Tutorials formatting + tensorclass example

- .github/workflows/docs.yml
- docs/Makefile
- docs/build_script.sh
- docs/requirements.txt
- docs/source/index.rst
- tutorials/sphinx_tuto/tensorclass_imagenet.py
This PR adds a tutorial demonstrating how tensorclasses can be used to load and manage ImageNet data in a training pipeline.
> [Docs] Imagenet tutorial

- docs/source/_templates/layout.html
- docs/source/conf.py
Updating the template and the config file to add badges (google colab, notebook, github link) to the sphinx documentation.
What types of changes does your code introduce? Remove all that do not apply:=
> [Doc] Adding external link badges to the documentation

- README.md
- docs/source/reference/generated/tensordict.LazyStackedTensorDict.rst
- docs/source/reference/generated/tensordict.SubTensorDict.rst
- docs/source/reference/generated/tensordict.TensorDict.rst
- docs/source/reference/generated/tensordict.nn.ProbabilisticTensorDictModule.rst
- docs/source/reference/generated/tensordict.nn.TensorDictModule.rst
- docs/source/reference/generated/tensordict.nn.TensorDictModuleWrapper.rst
- docs/source/reference/generated/tensordict.nn.TensorDictSequential.rst
- docs/source/reference/generated/tensordict.utils.expand_as_right.rst
- docs/source/reference/generated/tensordict.utils.expand_right.rst
Adds circleci and codevoc badges
> [Doc] Badges

- tensordict/nn/probabilistic.py
- test/test_tensordictmodules.py
> [BugFix] Use distribution kwargs

- benchmarks/distributed/dataloading.py
Some more changes to dataloading
> Dataloading amend

- tutorials/sphinx_tuto/tensorclass_imagenet.py
Fixes a minor rendering bug in the imagenet tutorial
> [BugFix, Doc] Minor fix in the doc

- tensordict/tensordict.py
- test/test_tensordict.py
> [BugFix] Shape change during prealloc

- tensordict/nn/functional_modules.py
- test/test_functorch.py
> [BugFix] Incorrect output batch_size with functorch.vmap

- benchmarks/common/memmap_benchmarks_test.py
- benchmarks/conftest.py
- benchmarks/requirements.txt
Adding some basic `MemmapTensor` benchmarks to assist work on #194
> [Benchmarks] Add MemmapTensor benchmarks

- tensordict/prototype/tensorclass.py
- tensordict/tensordict.py
- test/test_tensorclass_nofuture.py
- test/test_tensordict.py
Allows for tensor, int, float and tensordict/class comparison.
cc @apbard @tcbegley
> [BugFix] `__eq__` refactoring

- tensordict/prototype/tensorclass.py
- tensordict/tensordict.py
- test/test_tensorclass_nofuture.py
- test/test_tensordict.py
Implements `torch.gather` for `tensorclass` and `TensorDictBase`
> [Feature] Implement torch.gather for TensorDict and tensorclass

- test/test_tensorclass_nofuture.py
#203 fixed a bug but didn't include a dedicated regression test
> [Test, BugFix] add regression test for PR #203

- .circleci/config.yml
Reverts pytorch-labs/tensordict#225
> Revert "[CI] increase timeout for tests"

- docs/source/index.rst
- tutorials/sphinx_tuto/tensorclass_imagenet.py
- tutorials/sphinx_tuto/tensordict_preallocation.py
- tutorials/sphinx_tuto/tensordict_shapes.py
This PR adds a simple tutorial for pre-allocation.
> [Docs] Preallocation tutorial

- tensordict/nn/common.py
- tensordict/nn/probabilistic.py
- tensordict/tensordict.py
- test/test_tensordict.py
- test/test_tensordictmodules.py
Addresses https://github.com/pytorch/rl/issues/927
> [BugFix] Allow for nested output keys in Probabilitic modules

- docs/source/index.rst
- tutorials/sphinx_tuto/tensordict_slicing.py
This PR adds an indexing / masking tutorial. It is the last major bit of content to be moved out of the basic tutorial before we can deprecate that.
> [Docs, Tutorials] Add indexing tutorial

- tutorials/sphinx_tuto/tensordict_module.py
> [BugFix] Remove torchrl dependency from tutorials

- tensordict/tensordict.py
- test/test_tensordict.py
`Update_at_` was not tested and a wrong instance check was found in it.
> [BugFix] Uncaught wrong instance check in update_at_

- tensordict/tensordict.py
- test/test_tensordict.py
Allow `rename_key` to be called with nested keys
> [BugFix,Feature] Rename with nested keys

- tensordict/tensordict.py
- test/test_tensordict.py
Allow for memmap-like with heterogeneous tds.
> [BugFix] Memmap-like for lazy stacked tds

- benchmarks/tensorclass/torch_functions.py
This PR adds benchmarks for torch functions in tensorclasses that were used during development of #250
> [Tests] Add tensorclass benchmarks

- tensordict/tensordict.py
> [Doc] Remove no_check mentions in docstrings

- tensordict/tensordict.py
- test/test_tensordict.py
Solves a bug where lazy stacks fails to retrieve default value when requested
> [BugFix] Default value for lazy stack

- tensordict/tensordict.py
Calls `clear_device_()` recursively
> [BugFix] Recursively clear device

- tensordict/prototype/tensorclass.py
> [BugFix] `__getitems__` for tensorclass

- .pre-commit-config.yaml
- CONTRIBUTING.md
- docs/source/reference/nn.rst
- docs/source/reference/tensordict.rst
- mypy.ini
- tensordict/__init__.py
- tensordict/nn/common.py
- tensordict/nn/functional_modules.py
- tensordict/nn/probabilistic.py
- tensordict/prototype/fx.py
- tensordict/prototype/tensorclass.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensorclass_nofuture.py
- test/test_tensordict.py
This PR is aimed at keeping things separated between changes related to 0.1.0 release and bugfixes or doc formatting.
It's not a clean, self-contained PR...
> [Refactor] Cherry-pick changes from v0.1.0 before release

- tensordict/tensordict.py
> [BugFix] Fix reshape with empty shape

- tensordict/tensordict.py
- test/test_tensordict.py
Improves `make_tensordict` to allow its usage with nested dict / tensordict.
> [BugFix] Improve utils (pad_sequence and make_tensordict)

- tensordict/memmap.py
- test/test_memmap.py
> [BugFix] Fix memmap ownership to make it process-wise and allow for indexed memmap persistance

- docs/source/reference/nn.rst
- tensordict/nn/functional_modules.py
- test/test_functorch.py
Fixes calls to functional modules when params are still present in the module.
> [BugFix] Fix get_functional and functional call with stateful envs

- tensordict/nn/functional_modules.py
Function signature in functional modules is messed up.
> [BugFix] Fix function signature

- tensordict/nn/functional_modules.py
- tensordict/nn/probabilistic.py
This PR should fix the slow functional calls observed in some probabilistic modules
> [BugFix] Fix slow functional calls

- tensordict/nn/common.py
- test/test_nn.py
> [BugFix] dispatch with empty batch-size

- tensordict/persistent.py
- tensordict/tensordict.py
- test/test_tensordict.py
> [BugFix] Fix `__setitem__` with broadcasting of tensordicts

- tensordict/nn/probabilistic.py
- tensordict/tensordict.py
A bunch of efficiency improvements
> [Refactor] td.set and sampling efficiency

- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensordict.py
> [BugFix] Fix sub-tensordict indexing and updating

- benchmarks/common/common_ops_test.py
Benchmarks setitem and getitem
> [Benchmark] More item benchmarks

- .github/workflows/benchmarks.yml
Launch benchmarks when generate doc is created, not completed
> [CI] Continuous benchmark trigger

- .github/workflows/benchmarks.yml
> [CI] Continuous benchmark trigger (2)

- README.md
Closes #280.
The original work was done in a conda-forge PR (https://github.com/conda-forge/staged-recipes/pull/22307). 
> [Doc] Updated Docs with conda installation instruction

- tensordict/tensordict.py
Creating a td with a np.bool_ object raises a warning.
> [Refactor] Compatibility with np.bool_

- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensordict.py
> [BugFix] Fix none indexing

- tensordict/tensordict.py
- test/test_distributed.py
Implements a `reduce` operation for tensordict and tensorclass
> [Feature] tensordist.reduce

- tensordict/nn/common.py
- tensordict/nn/functional_modules.py
- test/test_nn.py
> [BugFix] Fix functional calls

- tensordict/memmap.py
This PR fixes a bug that arises when indexing `MemmapTensor` with a `torch.Tensor`. I found this investigating the bug reported in #382 which these changes fix.
The basic problem is that indexing a `numpy.memmap` with a `torch.Tensor` behaves differently to indexing with a `numpy.ndarray` or a list. For example
```python
>>> import numpy as np
>>> from tensordict import MemmapTensor
>>> t = torch.rand(3, 2, 1)
>>> mm = MemmapTensor.from_tensor(t)
>>> idx_list, idx_np, idx_tch = [0], np.array([0]), torch.tensor([0])
>>> print(t[idx_list].shape, t[idx_np].shape, t[idx_tch].shape)
torch.Size([1, 2, 1]) torch.Size([1, 2, 1]) torch.Size([1, 2, 1])
>>> print(mm[idx_list].shape, mm[idx_np].shape, mm[idx_tch].shape)
torch.Size([1, 2, 1]) torch.Size([1, 2, 1]) torch.Size([1, 2, …
```
> [Bugfix] Indexing memmaps with torch.Tensor

- tensordict/nn/common.py
- test/test_nn.py
Just bc @tcbegley needs more stamps
> [BugFix] Fix pickle PR

- tensordict/nn/common.py
- test/test_nn.py
> [Feature] Kwargs for tensordict modules

- setup.py
- tensordict/__init__.py
- tensordict/csrc/pybind.cpp
- tensordict/csrc/utils.h
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/conftest.py
- test/test_tensordict.py
Addresses https://github.com/pytorch/rl/issues/1247
> [Performance] Speed improvements

- .github/workflows/benchmarks_pr.yml
> [BugFix] Fix benchmarks in PR comparison

- benchmarks/common/common_ops_test.py
- benchmarks/common/memmap_benchmarks_test.py
- benchmarks/common/pytree_benchmarks_test.py
- benchmarks/distributed/distributed_benchmark_test.py
- benchmarks/nn/functional_benchmarks_test.py
- benchmarks/tensorclass/torch_functions.py
PR to decrease benchmark runtime
> [Refactor] Faster benchmarks

- tensordict/tensordict.py
> Revert "[Refactor] Better key membership check"

- benchmarks/common/common_ops_test.py
- tensordict/tensordict.py
To check that the solution to #469 isn't too bad
cc @matteobettini
> [Benchmark] Benchmark unbind

- tensordict/tensordict.py
Keep dim names in flatten / unflatten
> [BugFix] Unflatten names

- .circleci/unittest/rl_linux_optdeps/scripts/install.sh
- tensordict/__init__.py
- tensordict/csrc/pybind.cpp
- tensordict/csrc/utils.h
- tensordict/nn/common.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_nn.py
- test/test_tensordict.py
- test/test_utils.py
> [Refactor] unravel_key fixes

- .github/workflows/benchmarks.yml
I think unfortunately it no longer makes sense to ping me with these regressions. Perhaps there is someone else to whom I can pass the torch (pun not intended but enjoyed nonetheless 😄).
> Removing myself from notified users in benchmarks

- .gitignore
(And make the directories clearer)
> Add dist/ to gitignore.

- tensordict/memmap.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensordict.py
- test/test_utils.py
Removes support for list of bools as this is not supported by torch
> [BugFix] Fix indexing of lazy stacks

- tensordict/nn/params.py
- tensordict/persistent.py
- tensordict/tensordict.py
- tensordict/utils.py
- test/test_tensordict.py
Implements TensorDict.map which dispatches an operation over chunks of a tensordict along a chosen dimension.
Closes #504
> [Feature] TensorDict.map

- docs/source/saving.rst
- tensordict/nn/params.py
- tensordict/tensorclass.py
- tensordict/tensordict.py
- test/test_nn.py
- test/test_tensorclass.py
- test/test_tensordict.py
Fixes calls to state-dict to make them compatible with nn.Module.
Introduces related tests and docstring.
cc @matteobettini
> [BugFix] Fix state-dict

- .github/unittest/linux/scripts/install.sh
- test/test_tensordict.py
> [Test] Fix as_tensor test

- benchmarks/common/memmap_benchmarks_test.py
- tensordict/base.py
- tensordict/utils.py
- test/test_tensordict.py
> [Feature] Return early a tensordict created through memmap with multiple threads

- tensordict/_lazy.py
- tensordict/base.py
- tensordict/utils.py
- test/test_tensordict.py
Improves update_ when a subset of keys is to be updated
> [BugFix] Improve update_

- tensordict/_lazy.py
- tensordict/_td.py
- test/test_tensordict.py
> [BugFix,WIP] Fix indexing (lazy stack and names)

- docs/source/reference/tensordict.rst
- tensordict/utils.py
- test/test_utils.py
The method detects duplicate elements in the tensor associated with the specified 'key' along the specified
'dim' and removes elements in the same indices in all other tensors within the TensorDict.
> [Feature] Adds utils method remove_duplicates

- tensordict/_td.py
- test/test_tensordict.py
Solves https://github.com/huggingface/accelerate/issues/2405
> [Refactor, Feature] Default to empty batch size

- tensordict/_pytree.py
- tensordict/utils.py
- test/test_functorch.py
TODO:
Part of solution to https://github.com/huggingface/accelerate/issues/2405
> [Feature] td_flatten_with_keys

- tensordict/nn/probabilistic.py
Solves https://github.com/pytorch/rl/issues/1920
> [BugFix, Refactor] More reliable Sequential.get_dist

- tensordict/_td.py
- tensordict/_torch_func.py
- tensordict/base.py
- tensordict/tensorclass.py
- tensordict/utils.py
- test/test_tensordict.py
required by https://github.com/pytorch/rl/pull/1921
> [BugFix] Fix lazy params init

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
> [Feature] Allow non-tensordata to be shared across processes + memmap

- tensordict/nn/ensemble.py
Fixing the imports in the EnsembleModule docstring.
> [Doc] Fix EnsembleModule docstring

- tensordict/_td.py
- test/test_tensordict.py
> [BugFix] consistent use of non_blocking in tensordict and torch.Tensor

- tensordict/_td.py
- test/test_tensordict.py
Reverts pytorch/tensordict#731
> Revert "[BugFix] consistent use of non_blocking in tensordict and torch.Tensor"

- .github/unittest/linux/scripts/setup_env.sh
- .github/workflows/test-macos.yml
- tensordict/nn/probabilistic.py
Reverts pytorch/tensordict#754
> Revert "[Doc] Fix probabilistic td module doc"

- tensordict/_torch_func.py
- test/test_tensordict.py
> [BugFix] Fix gather device

- .github/workflows/nightly_build.yml
- .github/workflows/test-linux.yml
- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- benchmarks/distributed/dataloading.py
- tensordict/_td.py
- tutorials/sphinx_tuto/tensorclass_imagenet.py
Adds support for Python 3.12
fixes #766
> [CI] Python 3.12 compatibility

- .github/unittest/linux/scripts/run_test.sh
- .github/unittest/linux_torchrec/scripts/run_test.sh
- .github/unittest/rl_linux_optdeps/scripts/run_test.sh
- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/nn/common.py
- tensordict/nn/params.py
- tensordict/nn/sequence.py
- tensordict/nn/utils.py
- tensordict/utils.py
- test/test_compile.py
> [Feature] Compile - nn compatibility

- tensordict/_lazy.py
- tensordict/_torch_func.py
- test/test_tensordict.py
> [BugFix] Fix lazy stack indexing and split with empty slices

- tensordict/_lazy.py
- tensordict/base.py
- test/test_tensordict.py
> [Feature] lazy-stack with different TD shapes

- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #896
* #895
* #894
* #893
* #892
* __->__ #891
> [Feature] TD.new_zeros

- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #896
* #895
* #894
* #893
* __->__ #892
* #891
> [Feature] TD.new_ones

- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #896
* #895
* #894
* __->__ #893
* #892
* #891
> [Feature] TD.new_empty

- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #896
* #895
* __->__ #894
* #893
* #892
* #891
> [Feature] TD.new_full

- tensordict/_lazy.py
- tensordict/base.py
- tensordict/tensorclass.py
> [Feature] layout for get_nestedtensor

- tensordict/tensorclass.py
- tensordict/utils.py
> [Quality] Better `__repr__` for tensorclasses

- tensordict/_td.py
- tensordict/utils.py
> [BugFix] Fix bool indexing of lazy stacks when sub-tds are involved

- tensordict/base.py
- test/test_tensordict.py
* __->__ #909
cc @shagunsodhani
> [Feature] ``split_keys``

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #923
* #922
* #921
* __->__ #920
> [Feature] `reduce` arg in reductions

- tensordict/base.py
- test/test_tensordict.py
* #923
* #922
* __->__ #921
* #920
> [Feature] default for add, sub, pow, clamp_min, clamp_max, div and mul

- tensordict/base.py
* #923
* __->__ #922
* #921
* #920
> [Doc] Add docstrings to elementwise arithmetic ops

- tensordict/base.py
- test/test_tensordict.py
* __->__ #923
* #922
* #921
* #920
> [Feature] Symmetric errors in arithmetic ops

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/tensorclass.py
- test/test_tensordict.py
Eliminates cuda syncs since cuda stream can deal with it
> [BugFix] Simple syncs

- tensordict/_td.py
- tensordict/utils.py
> [BugFix] Fix key errors catch in del_ and related

- .github/unittest/linux/scripts/run_test.sh
- .github/unittest/rl_linux_optdeps/scripts/run_test.sh
- .github/workflows/benchmarks.yml
- .github/workflows/benchmarks_pr.yml
- .github/workflows/docs.yml
- docs/source/reference/tensordict.rst
- tensordict/__init__.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/nn/common.py
- tensordict/nn/distributions/composite.py
- tensordict/nn/functional_modules.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/utils.py
- test/_utils_internal.py
- test/test_tensordict.py
> [BugFix] Softly revert get changes

- benchmarks/compile/tensordict_nn_test.py
- tensordict/__init__.py
- tensordict/_contextlib.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/nn/params.py
- tensordict/nn/probabilistic.py
- tensordict/nn/utils.py
- tensordict/utils.py
- test/test_compile.py
- test/test_nn.py
- test/test_tensordict.py
> [BugFix] dynamo compat refactors

- tensordict/__init__.py
- tensordict/_lazy.py
- tensordict/_nestedkey.py
- tensordict/_nestedkey.pyi
- tensordict/_td.py
- tensordict/base.py
- tensordict/memmap.py
- tensordict/nn/common.py
- tensordict/nn/params.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/persistent.py
- tensordict/prototype/fx.py
- tensordict/tensorclass.py
- tensordict/utils.py
> [Quality] Type checks

- tensordict/nn/params.py
> [BugFix] restrict usage of Buffers to non-batched, non-tracked tensors

- tensordict/_contextlib.py
> [BugFix] Another compiler fix for older pytorch

- .github/workflows/build-wheels-aarch64-linux.yml
In order to close https://github.com/pytorch/rl/issues/2430
> [CI] Add aarch64-linux wheels

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/memmap.py
- tensordict/persistent.py
- tensordict/tensorclass.py
* __->__ #990
Required to close https://github.com/pytorch/rl/issues/2437
> [Feature] Propagate `existsok` in memmap* methods

- tensordict/nn/sequence.py
- test/test_nn.py
> [Feature] `selected_out_keys` arg in TDS constructor

- test/test_nn.py
> [Test] Rename duplicated test

- tensordict/memmap.py
> [BugFix] Remove ForkingPickler to account for change of API in torch.mp

- .github/workflows/docs.yml
- docs/Makefile
- docs/requirements.txt
- docs/source/conf.py
- docs/source/distributed.rst
- docs/source/index.rst
- docs/source/overview.rst
- docs/source/reference/nn.rst
- docs/source/reference/tensordict.rst
- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/memmap.py
- tensordict/nn/common.py
- tensordict/nn/cudagraphs.py
- tensordict/nn/distributions/composite.py
- tensordict/nn/probabilistic.py
- tensordict/nn/sequence.py
- tensordict/nn/utils.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/utils.py
- tutorials/sphinx_tuto/tensordict_shapes.py
> [Doc] Fail-on-warning in sphinx

- test/test_compile.py
- test/test_nn.py
> [Refactor, Tests] Move TestCudagraphs

- tensordict/base.py
- test/test_tensordict.py
> [Feature] `data_ptr()` method

- tensordict/nn/probabilistic.py
> [BugFix] Make probabilistic sequential modules compatible with compile

- tensordict/functional.py
- test/test_tensordict.py
> [Feature] callables for merge_tensordicts

- tensordict/_torch_func.py
> [BugFix] Propagate maybe_dense_stack in _stack

- benchmarks/common/h2d_test.py
> [Benchmark] Benchmark H2D transfer

- tensordict/nn/common.py
> [Feature] give a `__name__` to TDModules

- tensordict/_reductions.py
fixes: #1048
- [X ] I have raised an issue to propose this change ([required](https://github.com/pytorch/tensordict/issues) for new features and bug fixes)
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] I have read the [CONTRIBUTION](https://github.com/pytorch/tensordict/blob/main/CONTRIBUTING.md) guide (**required**)
> [BugFix] Remove forkingpickler

- tensordict/utils.py
> [Feature] Better logs of key errors in assert_close

- tensordict/nn/probabilistic.py
- test/test_nn.py
* #1118
* __->__ #1117
* #1114
> [Feature] ProbabilisticTensorDictModule.num_samples

- tensordict/_td.py
- tensordict/base.py
- test/test_tensordict.py
> [Doc,BugFix,Feature] Better doc for reductions

- .github/workflows/nightly_build.yml
* #1149
* __->__ #1148
* #1147
> [CI] Fix nightly build

- test/test_tensordict.py
> [Test] Ignore annoying jit_utils warning with device context manager

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-rl-gpu.yml
Same as https://github.com/pytorch/executorch/pull/7731
> Fix linux_job_v2 after https://github.com/pytorch/test-infra/pull/6104

- .github/workflows/docs.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-rl-gpu.yml
> [CI] Upgrade CUDA to 12.4

- tensordict/nn/distributions/composite.py
- tensordict/nn/probabilistic.py
> [BugFix] Better deterministic sample for composite

- tensordict/tensorclass.py
> [BugFix] Faster and safer non-tensor stack

- tensordict/utils.py
> [BugFix] `none` value for _CAPTURE_NONTENSOR_STACK

- tensordict/_lazy.py
- test/test_tensorclass.py
> [Test] Test dataclasses.field as tensorclass default

- tensordict/nn/sequence.py
- tensordict/tensorclass.py
- test/test_nn.py
> [Feature] inplace arg for TensorDictSequential

- tensordict/nn/sequence.py
- tensordict/tensorclass.py
> [BugFix] Fix tensorclass update

- .github/unittest/linux/scripts/environment.yml
- .github/unittest/linux/scripts/setup_env.sh
- .github/unittest/linux_torchrec/scripts/environment.yml
- .github/unittest/linux_torchrec/scripts/setup_env.sh
- .github/unittest/rl_linux_optdeps/scripts/environment.yml
- .github/unittest/rl_linux_optdeps/scripts/setup_env.sh
- .github/workflows/docs.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-rl-gpu.yml
- setup.py
> [CI,Setup] Fix CI and bump python3.13

- tensordict/_lazy.py
- tensordict/utils.py
- test/test_tensordict.py
> [Feature] view, flatten and unflatten for lazy stacks

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/nn/common.py
- tensordict/nn/probabilistic.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- test/test_tensordict.py
* #1265
* __->__ #1264
* #1263
> [Feature] as_list, as_padded_tensor and as_nested_tensor for Lazy stacks

- tensordict/base.py
- tensordict/nn/sequence.py
* #1268
* #1267
* __->__ #1266
> [Feature] NotImplemented for abstractmethods in base.py to avoid empty calls

- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/nn/sequence.py
- test/test_tensordict.py
* #1268
* __->__ #1267
* #1266
> [BugFix] fix replacing nested keys in rename_key_

- tensordict/nn/sequence.py
- tensordict/tensorclass.py
- test/test_tensorclass.py
* __->__ #1268
* #1267
* #1266
> [BugFix] fix get for tensorclass with lazy stacks

- setup.py
> [Setup] Fix setuptools error

- tensordict/_torch_func.py
- test/test_tensordict.py
* #1274
* #1273
* __->__ #1272
> [BugFix] *_like functions with dtypes

- tensordict/base.py
- test/test_tensordict.py
* #1274
* __->__ #1273
* #1272
> [Feature] Deepcopy

- tensordict/base.py
* __->__ #1274
* #1273
* #1272
> [BugFix] Fix rsub

- tensordict/_td.py
- tensordict/base.py
> [BugFix] Local cuda assessment

- tensordict/utils.py
> [BugFix] Fix .item() warning on tensors that require grad

- .github/unittest/linux/scripts/run_test.sh
- tensordict/_lazy.py
- tensordict/tensorclass.py
- test/test_tensorclass.py
- test/test_tensordict.py
> [BugFix] Better list assignment in tensorclasses

- test/test_compile.py
* #1290
* __->__ #1289
* #1288
> [Test] Deactivate failing test on 2.6

- .github/scripts/version_script.sh
- pyproject.toml
- test/test_nn.py
- test/test_tensorclass.py
> [CI] Fix 3.13t wheels

- .github/workflows/nightly_build.yml
> [CI] Fix nightly upload

- .github/workflows/nightly_build.yml
> [CI] Fix nightly version

- pyproject.toml
- tensordict/__init__.py
- tensordict/tensorclass.py
- tensordict/tensorclass.pyi
> [Setup] Fix version import

- tensordict/base.py
> [Feature] return_early for isend

- tensordict/_td.py
- tensordict/base.py
> [Performance] Second attempt at caching validation

- tensordict/_td.py
- tensordict/base.py
- tensordict/utils.py
- test/test_tensordict.py
> [BugFix] Fix improper name setting in `__setitem__`

- tensordict/_lazy.py
- test/test_tensordict.py
> [BugFix] new_* fix for Lazy stacks

- tensordict/_lazy.py
- tensordict/base.py
- tensordict/tensorclass.pyi
- test/test_tensordict.py
> [BugFix,Feature] new_* empty_lazy kwarg

- tensordict/_lazy.py
- tensordict/base.py
> [BugFix] Keeping names in new_* ops

- tensordict/nn/cudagraphs.py
> [Minor] Fix bad name in pytree warning

- test/test_nn.py
- test/test_tensorclass.py
- test/test_tensordict.py
> [Test] fbcode patches

- pyproject.toml
- tensordict/_lazy.py
- tensordict/_td.py
- tensordict/base.py
- tensordict/persistent.py
- tensordict/tensorclass.py
- tensordict/utils.py
Fixes bugs reported in https://github.com/pytorch/rl/issues/3053 and https://github.com/pytorch/rl/issues/3055
> [BugFix] JSON/orjson compatibility

- tensordict/__init__.py
- tensordict/_tensordict/__init__.py
- tensordict/nn/__init__.py
- tensordict/nn/distributions/__init__.py
As requested by @louisfaury and team!
> [Feature] Add __all__ everywhere

- tensordict/tensorclass.py
- test/test_tensorclass.py
> [BugFix] Fix ClassVar support in tensorclass

- .github/workflows/benchmarks.yml
- .github/workflows/benchmarks_pr.yml
- .gitignore
This PR fixes the benchmark CI upload issue by:
- Separating benchmark execution from upload
- Adding conditional upload for PRs with 'benchmarks/upload' label
- Running upload outside the container to avoid git issues
Testing the upload functionality in this PR.
> [CI] Fix benchmark CI upload with conditional PR testing

- tensordict/tensorclass.py
- test/test_tensorclass.py
> [BugFix] Args for TC with ClassVar

- tensordict/_td.py
close #1412
I also fixed some minor typing issues that triggers the pyright in my vscode with type narrowing.
> [Bugfix] Fix type annotation for tensordict.keys().__iter__() close #1412

- tensordict/tensorclass.py
Fix some errors in tensorclass decorator documentation.
NA
> [Doc] Fix tensorclass doc errors

- tensordict/_td.py
- tensordict/_torch_func.py
- test/test_tensorclass.py
Fixes https://github.com/pytorch/tensordict/issues/1454.
> [BugFix] Make tensordict.cat preserve TensorClass

- tensordict/_tensorcollection.pyi
- tensordict/base.py
- tensordict/tensorclass.pyi
Noticed some `dtype`-related typing was wrong.
close #1457
> [BUGFIX] Fix some `dtype` typing
