pytorch/tensordict

.github/workflows/nightly_build.yml, setup.py
This PR corrects a couple of typos in the nightly build workflow file and makes some modifications to `setup.py` in order to allow nightly builds and pushes to PyPI.
[I have manually run this workflow successfully](https://github.com/pytorch-labs/tensordict/actions/runs/3387628138) resulting in the nightly build of this package being [available on PyPI](https://pypi.org/project/tensordict-nightly/)
=> [Bug] Fix nightly build action

tensordict/tensordict.py, test/test_tensordict.py
Merge the instantiated sub-tensordict to the unflatted sub-tensordict to avoid collision.  
close #8 
=> [BugFix] Merge partial sub-tensordicts with flatten ones if unflattened

tensordict/tensordict.py, test/test_tensordict.py
This PR adds a new object `_TensorDictKeysView` which is returned when accessing `tensordict.keys()` and holds a reference to the original tensordict. This allows us to modify the behaviour of `key in tensordict.keys()` and use tuples for nested key lookups. For example
```python
import torch
td = TensorDict(
{"a": TensorDict({"b": torch.rand(1, 2)}, [1, 2]), "c": torch.rand(1)}, 
[1],
)
assert "a" in td.keys()
assert ("a",) in td.keys()
assert ("a", "b") in td.keys()
assert ("a", "c") not in td.keys()
```
This PR also disallows checks like `item in tensordict` except in the case of `tensordict in lazy_stacked_tensordict` where it will check if the tensordict is one of the tensordicts that will be lazily stacked when items are accessed.
=> [Feature] Add TensorDictKeysView

tensordict/metatensor.py, tensordict/tensordict.py, tensordict/utils.py, test/test_dim.py
This PR adds support for splitting / flattening TensorDict batch dimensions using first-class dimensions from functorch as raised in #14 
An example:
```python
td = TensorDict({"a": torch.rand(6, 3, 3)}, [6, 3])
d1, d2, d3 = dims(3)
d1.size = 3
td_dim = td[(d1, d2), d3]  # split first dimension in two
td2 = td_dim.order(d1, d2, d3)
assert td2.batch_size == torch.Size([3, 2, 3])
assert td2["a"].shape == torch.Size([3, 2, 3, 3])
d1, d2 = dims(2)
td_dim = td[d1, d2]
td2 = td_dim.order((d1, d2))
assert td2.batch_size == torch.Size([18])
assert td2["a"].shape == torch.Size([18, 3])
```
=> [Feature] Support splitting / flattening with first-class dims

tensordict/tensordict.py
Currently if import of `is_batchedtensor` from functorch fails, it will fail silently but the symbol `is_batchedtensor` remains undefined. This is causing tests on pytorch/rl#665 to fail.
[TorchRL solved this issue](https://github.com/pytorch/rl/blob/cd488b480d89d1df818bcaaadcef3e16b06434e2/torchrl/data/tensordict/tensordict.py#L72-L74) by defining a dummy `is_batchedtensor` function which always returns `False`. This PR restores that.
An alternative solution could be to use the unused `_has_functorch` variable to prevent `is_batchedtensor` being reached if the import has failed.
=> [Bugfix] Restore fallback for is_batchedtensor

tensordict/tensordict.py
Fixes a bug where the following code snippet tries to access the wrong meta-data dictionary
```python
td = TensorDict({'a': {'a': [1]}}, [])
print(list(td.items_meta()))
td.set(('a', 'a'), [2])
```
=> [BugFix] tensordict.set(nested_key, value) points to the wrong metadata dict

tensordict/tensordict.py, test/test_tensordict.py
This PR adds support for nested keys in `TensorDict.select`.
Example:
```python
>>> td = TensorDict({"nested": TensorDict({"a": torch.rand(1), "b": torch.rand(1)}, [])}, [])
>>> td.select(("nested", "b"))
TensorDict(
fields={
nested: TensorDict(
fields={
b: Tensor(torch.Size([1]), dtype=torch.float32)},
batch_size=torch.Size([]),
device=None,
is_shared=False)},
batch_size=torch.Size([]),
device=None,
is_shared=False)
```
cf. #22
=> [Feature] Support nested keys in select method

tensordict/tensordict.py, test/test_tensordict.py
**Note** This branch is currently targeting `nested-select` branch as it contains those changes also. #
This PR adds support for nested keys in `TensorDictBase.exclude()`. In the case of `LazyStackedTensorDict` we raise an exception if the keys aren't all strings until support for nested keys is added there more broadly.
cf. #22
=> [Feature] Support nested keys in exclude method

tensordict/tensordict.py, test/test_tensordict.py
Implements `tensordict.select(*keys, strict=False)` that allows for keys that are not present to be passed to select (in which case they are ignored).
=> [Feature] non-strict select

tensordict/tensordict.py, test/test_tensordict.py
Makes sure that the following use cases are coved:
```python
tensordict.update({"a": {"b": [1]}})
tensordict.update({("a", "b"): [1]})
tensordict.update({("a", "b"): [1], ("a", "c"): [1], })
```
=> [BugFix] Accept nested dicts for update

tensordict/nn/common.py, tensordict/tensordict.py, tensordict/utils.py, test/test_tensordictmodules.py
This PR adds support for nested keys to `TensorDictModule`. Much of the heavy lifting is done by existing support for nested keys in `set` and `get`. Here's a simple example:
```python
>>> import torch.nn as nn
>>> class Net(nn.Module):
...     def __init__(self, input_size=100, hidden=10):
...         super().__init__()
...         self.fc1 = nn.Linear(input_size, hidden)
...         self.fc2 = nn.Linear(hidden, 1)
... 
...     def forward(self, x):
...         x = torch.relu(self.fc1(x))
...         logits = self.fc2(x)
...         return torch.sigmoid(logits), logits
>>> module = TensorDictModule(
...     Net(),
...     in_keys=[("inputs", "x")],
...     out_keys=[("outputs", "probabilities"), ("outputs", "logits")],
... )
>>> x = torch.rand(5, 100)
>>> tensordict = …
```
=> [Feature] TensorDictModule nested keys

tensordict/nn/common.py, tensordict/tensordict.py, tensordict/utils.py, test/test_tensordict.py, test/test_tensordictmodules.py
Add support for nested keys to `.set_default` method.
Note that currently given a `LazyStackedTensorDict`, `set_default` will work if passed an existing key, but will fail when falling back to `set` which raises an error. Would it be better to raise an error earlier and disallow use of nested keys in `set_default` entirely?
cf. #22
=> [Feature] Nested keys support for set_default

tensordict/nn/common.py, tensordict/nn/sequence.py, tensordict/tensordict.py, tensordict/utils.py, test/test_tensordict.py, test/test_tensordictmodules.py
*Note*: this branches off `tensordictmodule-nested-keys` and so #48 should be merged first
This PR adds support for nested keys to `TensorDictSequential`. A simple example:
```python
>>> import torch.nn as nn
>>> from tensordict.nn import TensorDictModule, TensorDictSequential
>>> class Net(nn.Module):
...     def __init__(self, input_size=100, hidden_size=50, output_size=10):
...         super().__init__()
...         self.fc1 = nn.Linear(input_size, hidden_size)
...         self.fc2 = nn.Linear(hidden_size, output_size)
... 
...     def forward(self, x):
...         x = torch.relu(self.fc1(x))
...         return self.fc2(x)
>>> class Masker(nn.Module):
...     def forward(self, x, mask):
...         return torch.softmax(x * mask, …
```
=> [Feature] TensorDictSequential nested keys

README.md
The flatten keys example erroneously uses `unflatten_keys`.
=> [BugFix] Typo in README

tensordict/nn/common.py, tensordict/nn/probabilistic.py, tensordict/nn/sequence.py
This PR updates examples in docstrings for the new in-place functionalisation API and also deprecates the `make_functional_with_buffers` methods on probabilistic and sequential tensordict modules (these would break anyway since they call the `make_functional_with_buffers` method of the underlying modules which has already been deprecated.
=> [Feature] In-place functionalisation docstrings + cleanup

.github/workflows/docs.yml
This PR fixes the docs build workflow, as well as making some changes to make it more consistent with the other workflows in this repository.
Example output of the workflow can be seen on the [`gh-pages` branch on my fork](https://github.com/tcbegley/tensordict/tree/gh-pages).
Though this repo is not currently set up to host docs on GitHub pages, the idea is to pull built docs from this repo's `gh-pages` branch from the TorchRL repo where documentation will be hosted in the interim.
=> [Bugfix] Fix docs build workflow

setup.py
`pip install -e .` can lead to the following error
```
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... error
error: subprocess-exited-with-error
× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
error: Multiple top-level packages discovered in a flat-layout: ['gallery', 'packaging'].
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.
If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:
1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a …
```
=> [BugFix] Exclude potentially top-level packages from setup.py

tensordict/__init__.py
For internal usage we need the `__version__` attribute to be possibly None when the library is not installed using pip install.
=> [BugFix] Default version to None if not found

tensordict/nn/probabilistic.py, tensordict/nn/sequence.py, test/test_tensordictmodules.py
This PR contains changes to support adoption of `tensordict.nn.TensorDictModule` in TorchRL. It should not be merged in isolation.
cf. pytorch/rl#700
=> [NOMERGE] Migrate TorchRL to tensordict.nn.TensorDictModule

.circleci/config.yml, .circleci/unittest/linux_torchrec/scripts/environment.yml, .circleci/unittest/linux_torchrec/scripts/install.sh, .circleci/unittest/linux_torchrec/scripts/post_process.sh, .circleci/unittest/linux_torchrec/scripts/run-clang-format.py, .circleci/unittest/linux_torchrec/scripts/run_test.sh, .circleci/unittest/linux_torchrec/scripts/setup_env.sh, tensordict/metatensor.py, tensordict/tensordict.py, tensordict/utils.py, test/test_torchrec.py
KeyedJaggedTensor support.
Allows for indexing KJTs along the batch dimension, allowing them to be part of a TensorDict.
```python
>>> values = torch.Tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0])
>>> weights = torch.Tensor([1.0, 0.5, 1.5, 1.0, 0.5, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0])
>>> keys = ["index_0", "index_1", "index_2"]
>>> offsets = torch.IntTensor([0, 2, 2, 3, 4, 5, 8, 9, 10, 11])
>>> jag_tensor = KeyedJaggedTensor(
...    values=values,
...    keys=keys,
...    offsets=offsets,
...    weights=weights,
... )
>>> td = TensorDict({"b": jag_tensor}, [3])
>>> subtd = td[:2]
>>> assert subtd.shape == torch.Size([2])
>>> assert (
...     subtd["b", "index_0"].to_padded_dense()
...         == torch.tensor([[1.0, 2.0], [0.0, 0.0]])
...     ).all()
```
The `__getitem__` …
=> [Feature] TorchRec support: indexing keyedjaggedtensors

tensordict/tensordict.py, test/test_tensordict.py
- Implement `tensordict.split` method that works like [tensor.split](https://pytorch.org/docs/stable/generated/torch.split.html).
- Overload `torch.split` to support tensordict.
- Add test cases in `test_tensordict.py`
As requested in issue #28, It would be nice to have a tensordict.split method that would work as [tensor.split](https://pytorch.org/docs/stable/generated/torch.split.html).
We would also need to overload torch.split as we do for torch.stack if possible.
My changes involve a new function in API, the docstring is added to the function. The …
=> [Feature] `TensorDict.split` method

tensordict/nn/common.py, tensordict/nn/sequence.py
This PR makes some minor changes to fix bugs in the olddeps CI on pytorch/rl#700.
=> [BugFix] functorch fixes for old-deps

tensordict/nn/sequence.py
By creating a return value using `self.__class__`, child classes inheriting from `TensorDictSequential` will return an instance of the child type rather than `TensorDictSequential` without us having to redefine `select_subsequence`.
cf. pytorch/rl#700
=> [BugFix] TensorDictSequential inheritance fix

tensordict/tensordict.py, test/test_tensordict.py
This PR adds a new `leaves_only` kwarg (default False) to the `.keys`, `.values` and `.items` methods of `TensorDict` and subclasses. When set to True, keys and values corresponding to nested tensordicts are omitted from the iteration (though their children are not).
Example
```python
import torch
td = TensorDict({"a": torch.rand(1), "b": TensorDict({"c": torch.rand(1)}, [])}, [])
assert set(td.keys(include_nested=False, leaves_only=False)) == {"a", "b"}
assert set(td.keys(include_nested=True, leaves_only=False)) == {"a", "b", ("b", "c")}
assert set(td.keys(include_nested=False, leaves_only=True)) == {"a"}
assert set(td.keys(include_nested=True, leaves_only=True)) == {"a", ("b", "c")}
```
=> [Feature] Add leaves_only kwarg to keys / values / items methods

tensordict/tensordict.py, test/test_tensordict.py
This PR adds `insert` and `append` methods to `LazyStackedTensorDict` corresponding to the analogous methods for `list`.
Under the hood `append` simply calls `insert` with `index = len(self.tensordicts)`. While `my_list.insert(len(my_list), item)` is fractionally slower than `my_list.append(item)`, this is dwarfed by the checks which I think it makes sense to share.
Example:
```python
>>> td = TensorDict({"a": torch.zeros(4)}, [4])
>>> lstd = torch.stack([td] * 2)
>>> lstd.insert(1, TensorDict({"a": torch.ones(4)}, [4]))
>>> lstd["a"]
tensor([[[0.],
[0.],
[0.],
[0.]],
[[1.],
[1.],
[1.],
[1.]],
[[0.],
[0.],
[0.],
[0.]]])
```
=> [Feature] Lazystack insert / append

docs/source/index.rst, docs/source/overview.rst
This PR adds overview of `tensordict` and `tensordict.nn` to documentation.
Local build:
=> [Docs] Add TensorDict overview to docs

tensordict/nn/prototype.py, test/test_tensordictmodules.py
This PR makes changes to `ProbabilisticTensorDictModule` and adds a new class `ProbabilisticTensorDictSequential`.
`ProbabilisticTensorDictModule` is now a pretty lightweight class which reads distribution parameters from a tensordict. A foward pass writes a sample to the output tensordict, whereas `get_dist` method can be used to recover the distribution object.
`ProbabilisticTensorDictSequential` is much like `TensorDictSequential`, but the final module in the sequence must always be a `ProbabilisticTensorDictModule`. We then additionally expose the `get_dist` method which allows the user to perform a forward pass of the sequence to get distribution parameters, and then return the resulting distribution.
=> [Feature] Refactor probabilistic module wrapper

tensordict/nn/functional_modules.py
Fixes a bug where nn.Module with no forward method fail to be serialized/deserialized if they have been functionalized.
For the record, the error reads:
```
AttributeError: 'ModuleList' object has no attribute '_forward_unimplemented'
```
This is due to the fact that an nn.Module.forward is defined as
```
def _forward_unimplemented(self, *args):
etc.
class nn.Module():
forward = _forward_unimplemented
```
We expect this bug to occur every time a forward method is written outside of the module and assigned subsequently.
The current patch only fixes the `_forward_unimplemented`-related error.
cc @tcbegley
=> [BugFix] patched nn.Module deserialization

docs/source/reference/nn.rst, tensordict/nn/__init__.py, tensordict/nn/common.py, tensordict/nn/sequence.py, tensordict/tensordict.py, test/test_tensordictmodules.py
Refactors `dispatch_kwargs` for a completely `TensorDict` oblivious behviour.
Allows to call a TDModule, TDSequential or any other module decorated with `dispatch_kwargs` with a set of keyword arguments. The function will return a tuple or tensors or a single tensor, depending on the number of module outputs.
@tcbegley
=> [Refactor] Refactor dispatch_kwargs for easier usage

tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
This PR creates a new `_TensorClassMeta` metaclass, which checks the dataclass field names against reserved TensorDict attributes / methods when the class is defined, rather than when the first instance is created.
This prevents users from being able to define a class that could never be instantiated without error, and moves the error closer to the source of the problem.
cc: @roccajoseph
=> [Feature] Add metaclass for TensorClass instances

tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
This PR allows the user to specify `device` when instantiating a TensorClass (`@tensorclass` decorated dataclass).
=> [Feature] Tensorclass device

tensordict/prototype/__init__.py, tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
This PR makes a few updates to tensorclasses. An earlier version of these changes introduced a new base class which I have now removed again.
The main things to note
1. I've added properties corresponding to `batch_size` and `device` which allow them to be set as in the case of `TensorDict`.  Note the necessary change in `__setattr__` which unlike `__getattr__` is called whether or not the attribute exists. Also note that `batch_size` is no longer one of the dataclass fields. I think this makes sense as the fields should correspond to keys in the tensordict and hence not include `batch_size`.
2. I've added a new `is_tensorclass` helper function to enable type checking of tensorclasses and tensorclass instances. It is based on `dataclasses.is_dataclass` in the Python standard library (and …
=> [Feature] Tensorclass updates

test/test_functorch.py
Some test use functorch's vmap function. Currently, this is defined only if functorch is available. Thus, we need to skip all related tests if functorch is not available
=> [BugFix] add skipif not _has_functorch

tensordict/metatensor.py, tensordict/tensordict.py, test/test_tensordict.py
Allows to construct LazyStackedTensorDict instances containing entries with the same key but different shape.
These entries will raise an exception when queried with `get` or functions that (indirectly) call `get`, but a proper error message will point to the solution (i.e. using `get_nestedtensor`).
Partially solves
https://github.com/pytorch/rl/issues/766
cc @matteobettini
=> [Feature] Stacking tensors of different shape

tensordict/tensordict.py, test/test_tensordict.py
This PR fixes a bug that arose when indexing a `LazyStackedTensorDict` along its stacking dimension.
We detect whether the stacking dimension is included in the dimensions being indexed, index the list of tensordicts, and then apply the remaining indices as necessary. This seemingly was attempted in the original implementation, but there was a logic error with remaining indices not being applied after the list had been indexed.
Previous behaviour
```python
>>> td = TensorDict({"a": torch.rand(3, 4), "b": torch.rand(3, 4)}, [3, 4])
>>> td = torch.stack([td, td, td], 1)
>>> print(td[2, 2])
TensorDict(
fields={
a: Tensor(torch.Size([3, 4]), dtype=torch.float32),
b: Tensor(torch.Size([3, 4]), dtype=torch.float32)}, …
```
=> [BugFix] LazyStackedTensorDict indexing along stack_dim

tensordict/tensordict.py, test/test_tensordict.py
This PR adds support for `range` in indexing operations, both get and set.
E.g.
```python
>>> td = TensorDict({"a": [1, 2, 3, 4, 5]}, [5])
>>> print(td[range(2)])
TensorDict(
fields={
a: Tensor(torch.Size([2]), dtype=torch.int64)},
batch_size=torch.Size([2]),
device=None,
is_shared=False)
>>> td[range(2)] = TensorDict({"a": [0, 0]}, [2])
>>> print(td["a"])
tensor([0, 0, 3, 4, 5])
```
=> [Feature] Support `range` in indexing operations

tensordict/tensordict.py, test/test_tensordict.py
This PR fixes the failing tests on main arising from the merging of #139 and #140.
#140 introduced a new test class `nested_stacked_td` with stack dimension `1` to `TestTensorDictsBase` which surfaced issues with stack dimension indexing in `LazyStackedTensorDict`. In brief, whatever was used to index the stack dimension was simply used to index the underlying list at `self.tensordicts`. Thus while numbers and slices worked fine, you would get an error if you tried to index the stack dimension with a list, tensor, or `range` object.
With these changes, things should now work as expected.
=> [BugFix] Stack dimension indexing

tensordict/tensordict.py, test/test_tensordict.py
This PR prevents the user from calling `LazyStackedTensorDict.get_nestedtensor` unless `stack_dim` is `0`. 
I did wonder whether it should be allowed in the case where each item under that key had the same shape (in which case it would be possible to return the result of a call to `torch.stack`), but I figured that it would be surprising to get a regular tensor rather than a nested tensor from a call to `get_nestedtensor`.
=> [BugFix] Prevent calls to get_nestedtensor when stack_dim is not 0

tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
Previously `len(my_tensorclass)` would result in an error `TypeError: object of type 'MyTensorClass' has no len()`.
This PR adds a `__len__` method to generated tensorclasses that falls back to the underlying tensordicts `__len__` method.
=> [BugFix] Add __len__ method to tensorclass

docs/source/overview.rst
Fixes typo in key (`outputs` -> `output` ) that made example unrunnable.
Also corrects some under-indentation to ease copy-pasting the example code.
=> [Docs] Typo and formatting in overview example

tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
This PR updates how we create dataclasses. Instead of locally defining a class and returning that, we modify the decorated class in place. The motivation is:
1. Returning a locally defined class leads to errors when we try to pickle instances of those classes.
2. The new behaviour is closer to the behaviour of `dataclasses.dataclass` and hence less surprising to users.
While refactoring I noticed a bug with how default_factory values were handled which I have fixed.
```python
import pickle
import torch
from tensordict.prototype import tensorclass
from tensordict.tensordict import assert_allclose_td
@tensorclass
class Data:
value: torch.Tensor
def square_value(self):
return self.value ** 2
d = Data(value=torch.rand(5, 10), batch_size=[5])
with open("test.pkl", "wb") as f:
pickle.dump(d, f) …
```
=> [BugFix] Create TensorClass by modifying decorated class in-place

tensordict/prototype/tensorclass.py
Noticed a small bug in the definition of tensorclass' `__ne__` method. I don't think it was actually reachable though...
If we fail the first if statement, we are guaranteed to pass the second (because `other` must be an instance of `self.__class__` and hence `is_tensorclass` will be `True`). So we'll always hit one of the first two return statements.
In some sense then, the bugfix is irrelevant. I think we could probably refactor this to
```python
def __eq__(self, other):
if not isinstance(other, self.__class__):
return False
return self.tensordict == other.tensordict
```
or the even more compact
```python
def __eq__(self, other):
return isinstance(other, self.__class__) and self.tensordict == other.tensordict
```
We also could drop `__ne__` completely because default behaviour of …
=> [BugFix] Typo in tensorclass.__ne__

tensordict/prototype/tensorclass.py, test/test_tensorclass.py, test/test_tensorclass_nofuture.py
This PR refactors the generated init method of tensorclasses. The motivation was to try and make the signature less confusing. 
Previously `batch_size` was a positional or keyword argument with default value `None`, however, usually if `batch_size` was not specified, this would lead to a `ValueError`, so during normal instantiation `batch_size` was a required argument.
However, `batch_size` was **not** required if the user constructed a tensorclass by passing a `TensorDict` via the `_tensordict` argument.  Hence it was not possible for us to make `batch_size` a required argument.
The changes:
- `batch_size` is now a required keyword-only argument. If you don't specify it, Python will raise a `TypeError`.
- There is no longer a `_tensordict` argument in tensorclass constructors.
- …
=> [Refactor] TensorClass drop _tensordict argument in constructor

test/test_tensorclass_nofuture.py
Relax error matching in TensorClass tests. Largely motivated by FBCode compatibility, but since #165 the need to check the representation of types in error messages is less important anyway.
=> [BugFix] Relax error matching in tensorclass tests

tensordict/nn/probabilistic.py, test/test_tensordictmodules.py
Using `set_interaction_mode` as a decorator did not have the desired behaviour bc the `clone` method had to be adapted.
=> [BugFix] Using set_interaction_mode as decorator

tensordict/memmap.py, tensordict/tensordict.py, test/test_memmap.py, test/test_tensordict.py
Allows to call `apply` across multiple TDs.
EDIT:
As pointed in the conversation below, this highlighted a bug with `MemmapTensor` created from other `MemmapTensor`s. The whole thing was becoming messy and I changed the way `MemmapTensor` are built as a result of this.
This IS BC-breaking:
```python
MemmapTensor(tensor)  # not allowed anymore
MemmapTensor.from_tensor(tensor)  # proper way to do it
MemmapTensor.from_tensor(memmap_tensor)  # returns memmap_tensor (without copy)
```
We would need to see what to do with #189: I would guess that `from_tensor` could take other arguments, such as the destination etc. If any of these suggests that a copy must be done, then it will be.
Wdyt @tcbegley?
Closes #181 
cc @Daxo32
=> [Feature] apply across multiple TDs

test/test_memmap.py
This PR fixes a bug that arises when you construct one `MemmapTensor` from another which I noticed while working on #189 
Repro:
```python
>>> from tensordict import MemmapTensor
>>> mt = MemmapTensor(4, 3, 2, 1)
>>> assert mt.squeeze(-1).shape == torch.Size([4, 3, 2])  # this is fine
>>> mt2 = MemmapTensor(mt)
>>> mt2.squeeze(-1)  # AttributeError: squeeze not found
```
Issue is that internal attribute `self._tensor_dir` was constructed from `elem.__dir__()`, but this leads to attributes not being found.
=> [BugFix] MemmapTensor from MemmapTensor __dir__ issue

docs/source/saving.rst, tensordict/memmap.py, tensordict/tensordict.py, test/conftest.py, test/test_memmap.py, test/test_tensordict.py
This PR addresses #178 by adding more arguments to the `MemmapTensor` constructor, and making the behaviour of `TensorDict.memmap_` richer when `prefix` is specified.
In brief:
- `MemmapTensor` now accepts two additional arguments: `filename` and `mode`.
- `filename` determines the location on disk of the underlying `memmap`.
- `mode` determines the opening mode of the underlying `memmap`. Options are `"r+"`, `"w+"` and `"c"` as well as their verbose equivalents. This is what `numpy.memmap` supports with the exception of `"r"` as `torch.Tensor` gets quite unhappy if the underlying NumPy array is not writable.
- `TensorDict.memmap_` with a specified `prefix` will now locate the contents of the tensordict in the specified directory, with a nested structure determined by the keys in the …
=> [Feature] More arguments for MemmapTensor construction

tensordict/prototype/tensorclass.py
A type check in `_setitem` blocks MemmapTensors from being written on tensors or conversely.
Tensor types should not match when setting an item at an index.
cc @apbard @sreevasthav
=> [BugFix] tensorclass `__setitem__` must allow non-type stringent writing

tensordict/tensordict.py, test/test_tensordict.py
This PR fixes the recursive `to_dict` method of `TensorDict`. This is possible by addition of two new helper functions `_dict_get_nested` and `_dict_set_nested` which allow us to easily get and set nested keys in a regular Python `dict`.
I have modified `_TensorDictKeysView` to optionally return metadata about auto-nested keys so that the auto-nested structure can be preserved in the resulting dict.
cc @ruleva1983
=> [BugFix][Auto-nested] Fix `to_dict` method

.circleci/config.yml
torchrec tests consistently fail due to upstream library. We should disable them until upstream is fixed and they can pass
=> [CI] Temporarily disable torchrec tests

tensordict/utils.py, test/test_utils.py
This PR fixes various bugs I encountered in `_getitem_batch_size` where for particular choices of index the following test would fail
```python
assert tensor[index].shape == _getitem_batch_size(tensor, index)
```
I first noticed this in the case where the index was a tuple of tensor-like indices. Indeed something as simple as
```python
tensor = torch.rand(2, 2)
index = ([0], [0])
assert tensor[index].shape == _getitem_batch_size(tensor, index)
```
currently fails on `main`. The correct behaviour when there are tuples of tensor-like indices present is to broadcast them onto a common shape, and then extract the diagonal entry. So `tensor[list1, list1]` is roughly equivalent to `torch.stack([tensor[i, j] for i, j in zip(list1, list2)])`. The final shape depends slightly on whether those …
=> [BugFix] Fix `_getitem_batch_size` in various edge cases.

test/conftest.py, test/test_memmap.py, test/test_tensorclass_nofuture.py, test/test_tensordict.py
I am switching from tmpdir to the new tmp_path fixture.
@tcbegley, @vmoens is there a reason we were defining our custom tmpdir instead of using the regular pytest one?
=> [Test] use temp_path instead of tmpdir

tensordict/tensordict.py
Fixes some edge cases where `zero` is being called with an expanded empty shape, thereby missing the input shape altogether.
=> [BugFix] Calling zeros with an empty batch size

tensordict/tensordict.py, test/test_tensordict.py
This PR adds a new decorator `_recursion_guard` which catches recursion errors in methods that don't currently support auto-nesting and adds a more instructive error message.
I've removed skips from a number of methods that are in fact working. I've also removed some skips from tests which were failing for reasons that should be fixed rather than because they were testing for unsupported behaviour. Reasons for failures are listed below. I did this because otherwise I think we could trick ourselves into thinking that #201 is ready to be merged into main prematurely.
The following tests fail because `assert_allclose_td` does not support auto-nested values
- `test_from_empty`
- `test_masking`
- `test_getitem_ellipsis`
- `test_getitem_range`
The following tests fail because we can't …
=> Add recursion guard and tidy tests

.circleci/config.yml
Some tests are failing due to timeout. This extends timeout threshold
=> [CI] increase timeout for tests

test/test_memmap.py
Solves the tests failing with python 3.10 and mp tests with memmap tensors
=> [BugFix] Fix infinite loop in memmap tests

docs/source/index.rst, tutorials/sphinx_tuto/tensordict_shapes.py
This PR adds a simplified and self-contained tutorial for reshaping tensordicts.
There is currently some redundancy between this and `tensordict_basics.py`. I think ultimately the latter should be deleted / completely split up before #221 is merged.
=> [Docs] Add simplified reshape tutorial

tensordict/tensordict.py, test/test_distributed.py, test/test_tensordict.py
Fixes cases where the key order mismatch between a src and dest tensordict.
The `sorted_keys` attribute is intentionally not adapted to `tensorclass` as this would require to duplicate a lot of code + we will probably refactor tensorclass soon.
=> [BugFix] Fix sorting of keys in send and recv

tensordict/tensordict.py, test/test_tensordict.py
This PR renames `set_default` to `setdefault` for parity with Python's `dict`.
I've actually left `set_default` in place for now with a deprecation warning as TorchRL uses `setdefault` and so we would break their CI with a straight switch. Once this lands, we can update TorchRL, then drop the alias here and hopefully not cause any disruption.
=> [Refactor] Rename set_default -> setdefault

docs/source/index.rst, tutorials/sphinx_tuto/tensordict_module.py, tutorials/sphinx_tuto/tensordict_module_functional.py
This PR extracts the functional parts of the `TensorDictModule` tutorial into their own tutorial.
=> [Docs, Tutorials] Split functional content from module tutorial

tensordict/tensordict.py
While working on the tutorials I noticed that `clear_device` doesn't return anything, unlike the closely related `to` method.
This small change returns `self`, allowing `clear_device` to be chained with other methods.
=> [BugFix] Return self from `clear_device`

tensordict/prototype/tensorclass.py, tensordict/tensordict.py, test/_utils_internal.py, test/test_tensorclass_nofuture.py, test/test_tensordict.py
- Allows for tensorclass instances to be used as values for a TensorDict
- Adds a series of tests for this use case
- Removes the tensorclass instances from `tensorclass._non_tensordict`
=> [Feature] Nesting tensorclass instances in tensordicts

tutorials/sphinx_tuto/tensorclass_fashion.py
As of #150 this is not needed, so removing from tutorial to avoid confusion.
=> [Docs] Remove unneeded __len__ definition in tutorial

tensordict/prototype/tensorclass.py, tensordict/tensordict.py
This PR reduces boilerplate in tensorclass methods. Many of them copy the metadata or replace entries with `None`. Here we create two helper functions that can be called from inside the methods to streamline the code.
=> [Refactor] Reduce boilerplate in tensorclass methods

tensordict/nn/__init__.py, tensordict/nn/common.py, tensordict/nn/sequence.py, test/test_nn.py
Adds a `source` and `dest` keyword arguments to `dispatch` (renamed from `dispatch_kwargs`).
One can also call the module with unnamed arguments.
Renames the `test_tensordictmodule.py` in `test_nn.py` which is clearer.
=> [Feature] Add dispatch source and dest arguments

tutorials/sphinx_tuto/tensorclass_imagenet.py
Doc fails to get built due to a call to pin_memory in a script executed on a cpu machine
=> [Doc, BugFix] pin-memory call on cpu only scripts

benchmarks/common/common_ops_test.py, tensordict/tensordict.py, test/test_tensordict.py
`select` currently misses the nested `("a", "b")` in this case:
```python
td = TensorDict({"a": {"b": [1], "c": [2]}}, [])
td_select = td.select(("a", "b"), "r", ("a", "z"), strict=False)
assert ("a", "b") in td_select.keys(True, True)
```
=> [BugFix] Select misses nested keys if missing nested are present

tensordict/prototype/fx.py, tensordict/tensordict.py, test/test_tensordict.py
This PR refactors `set` and its variants (`set_`, `set_at_` etc.), the primary goals being:
- Make it clearer which methods have responsibility to perform input validation, particularly with a view to ensuring that we're not incurring unnecessary overhead by duplicating checks
- Create a new private method `_set` which can be used to bypass runtime checks, in favour of passing around a flag `_run_checks`.
The basic idea is to have methods for validation of keys and values, perform the validation, and delegate the actual setting logic to `_set`. Something like
```python
def set(self, key, value, inplace=False):
key = self._validate_key(key)
value = self._validate_value(value)
return self._set(key, value, inplace=inplace)
```
There are some difficulties here though. The first is with nested …
=> [Refactor] Refactor set methods

tensordict/tensordict.py, test/test_tensordict.py, tutorials/sphinx_tuto/tensordict_keys.py
This PR appends `_` to various methods that are inplace in order to match the PyTorch convention.
There are some that are arguably inplace but which I have not changed in order to match corresponding methods in PyTorch, namely:
- `recv`
- `irecv`
- `load_state_dict`
=> [Refactor] Inplace methods

tensordict/nn/common.py, tensordict/tensordict.py, test/test_nn.py, test/test_tensordict.py
`TensorDictModule` allows some arguments to be missing in the input tensordict, in which case a `None` value is used.
The error message that occurs if that value is actually necessary is misleading, always being something like "NoneType has no attribute shape" or similar.
We now capture errors, check if any input is None and if the error contains None, and turn the error message to something more indicative of what is going on.
Similarly, we capture errors like
```python
td = TensorDict({"a": torch.zeros(())}, [])
td["a", "b"]
```
to let users know what is going on with the wrongful indexing.
Suggestions are welcome!
=> [Quality] More informative error message when an argument is None in TensorDictModule

tensordict/tensordict.py
Some changes in tensordict construction aimed at speeding it up.
Some benchmarks:
```python
import timeit
import torch
make_td1 = """
TensorDict({
'a': {'1': {'2': {'3': torch.zeros(())}}},
'b': {'1': {'2': {'3': torch.zeros(())}}},
'c': {'1': {'2': {'3': torch.zeros(())}}},
'd': {'1': {'2': {'3': torch.zeros(())}}},
'e': {'1': {'2': {'3': torch.zeros(())}}},
'f': {'1': {'2': {'3': torch.zeros(())}}},
'g': {'1': {'2': {'3': torch.zeros(())}}},
'h': {'1': {'2': {'3': torch.zeros(())}}},
'i': {'1': {'2': {'3': torch.zeros(())}}},
'j': {'1': {'2': {'3': torch.zeros(())}}},
'k': {'1': {'2': {'3': torch.zeros(())}}},
'l': {'1': {'2': {'3': torch.zeros(())}}},
'm': {'1': {'2': {'3': torch.zeros(())}}},
'n': {'1': {'2': {'3': torch.zeros(())}}},
}, [])
""" …
```
=> [Refactor] Speedup construction

.github/workflows/selfassign.yml
Commenting `#self-assign` in any issue will let repository members to self-assign that issue to themselves.
:point_right: This reduces chores for repo-maintainer(s).
**Why is this change required? What problem does it solve?**
- :tada: This reduces some administrative overhead and makes it quicker for any contributor to self-assign an issue and start working on it.
- Closes #282 
*Will it be okay if the `CONTRIBUTING.md` file is updated with this feature for issue-self-assigning?*
=> [CI] Added workflow to let contributors self-assign issues

tensordict/tensordict.py, test/test_tensordict.py
`TensorDict.reshape` calls `TensorDict.view` when the shape is not expanded.
=> [BugFix] Fix reshape with non-expanded sizes

tensordict/tensordict.py, test/test_tensordict.py
Ensures that the following methods work the same way:
```python
input_dict = {
"a": {"b": torch.randn(3, 4), "c": torch.randn(3, 4, 5)},
"d": torch.randn(3),
}
tensordict = make_tensordict(input_dict)
input_dict = {
("a", "b"): torch.randn(3, 4),
("a", "c"): torch.randn(3, 4, 5),
"d": torch.randn(3),
}
tensordict = make_tensordict(input_dict)
```
=> [BugFix] make_tensordict batch-size with tuple keys

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux_stable/scripts/environment.yml, .circleci/unittest/linux_torchrec/scripts/environment.yml, docs/source/reference/tensordict.rst, setup.py, tensordict/__init__.py, tensordict/memmap.py, tensordict/persistent.py, tensordict/tensordict.py, tensordict/utils.py, test/_utils_internal.py, test/test_distributed.py, test/test_fx.py, test/test_h5.py, test/test_memmap.py, test/test_tensorclass_nofuture.py, test/test_tensordict.py, test/test_utils.py
Test:
```python
import numpy as np
import h5py
from tensordict import PersistentTensorDict
arr = np.random.randn(1000)
with h5py.File('groups.hdf5', 'w') as f:
g = f.create_group('Base_Group')
gg = g.create_group('Sub_Group')
d = g.create_dataset('default', data=arr)
dd = gg.create_dataset('default', data=arr)
td = PersistentTensorDict(filename='groups.hdf5', batch_size=[1000])
print(td.get(("Base_Group", "Sub_Group", "default"))[:2])
print(td[:2]["Base_Group", "Sub_Group", "default"])
print(td[:2]["Base_Group", "Sub_Group"]["default"])
print(td["Base_Group"])
print(td)
td = PersistentTensorDict(filename='groups.hdf5', batch_size=[3])
print(td)  # raises an exception
```
Follow up:
=> [Feature] h5 compatibility

tensordict/prototype/tensorclass.py, test/test_tensorclass_nofuture.py
set and set_at_ are broken for non-tensor / optional fields. This PR solves this.
Example code:
```python
from __future__ import annotations
import torch
from tensordict.prototype import tensorclass
@tensorclass
class Data:
opt0: torch.Tensor | str | None = None
opt1: torch.Tensor | str | None = None
d = Data(opt0=torch.randn([3,5]), batch_size=[3])
d.set("opt1", torch.randn([3,3]))
d = Data(batch_size=[3])
d[0] = Data(opt0=torch.randn(()), opt1=torch.randn(()), batch_size=[])
print(d[0].opt0)
print(d.opt1)
```
=> [BugFix] add set/get and set_at,get_at methods to tensorclass

tensordict/nn/functional_modules.py, tensordict/tensordict.py, test/test_nn.py
Our implementation is now 1.3s vs 2s previously.
torch functional call is still at 0.8s on my mcbook, so there is room for improvement.
```python
import timeit
import torch
from torch import nn
from tensordict.nn import make_functional
def make_module():
module = torch.nn.Sequential(
nn.Linear(4, 4),
nn.ReLU(),
nn.Linear(4, 4),
nn.ReLU(),
)
return module
x = torch.randn(4)
module = make_module()
parameter_and_buffer_dicts = module.state_dict()
v1 = torch.func.functional_call(module, parameter_and_buffer_dicts, (x,))
t0=timeit.timeit("torch.func.functional_call(module, parameter_and_buffer_dicts, (x,)), ", globals={
"module": module,
"parameter_and_buffer_dicts": parameter_and_buffer_dicts,
"x": x,
"torch": torch,
}, number=10_000)
params = make_functional(module)
v2 = module(x, params) …
```
=> [Refactor] Faster functional module

docs/source/reference/nn.rst, tensordict/nn/__init__.py, tensordict/nn/probabilistic.py, test/test_nn.py, tutorials/sphinx_tuto/tensordict_module.py
Replaced `<*>interaction_mode` class/fcn/args with `<*>interaction_type` for better naming clarity. Added depreciated warnings to existing usage of `interaction_mode` for backward compatibility.
This is to address https://github.com/pytorch/rl/issues/1016 
* `pytest test/`
=> Deprecate interaction_mode with interaction_type

tensordict/nn/sequence.py
Use `key in tensordict.keys()` inside `TensorDictSequential` instead of collecting keys into a `set`.
The old way of doing things causes problems when using `TensorDictSequential` on a `LazyStackedTensorDict` with some entries that can't be stacked, even if they are not used by the sequential module. See example below
```python
import torch
import torch.nn as nn
from tensordict.nn import TensorDictModule, TensorDictSequential
tds = [
TensorDict({"in": torch.rand(10, 3), "other": torch.rand(10, 2)}, batch_size=[10]),
TensorDict({"in": torch.rand(10, 3), "other": torch.rand(10, 5)}, batch_size=[10]),
]
td = torch.stack(tds, 0)
module1 = TensorDictModule(nn.Linear(3, 5), ["in"], ["intermediate"])
module2 = TensorDictModule(nn.Linear(5, 1), ["intermediate"], …
```
=> [BugFix] Key checks in TensorDictSequential

tensordict/nn/probabilistic.py
This PR adds the `dispatch` decorator to probabilistic variants of `TensorDict{Module,Sequential}` in order that they may be used with positional / keyword tensor arguments as well as tensordicts.
Happy to add tests if you think they're needed.
=> [BugFix] Add dispatch decorator to probabilistic modules

tensordict/nn/probabilistic.py
This PR adds `sample_log_prob` to the `out_keys` of a `ProbabilisticTensorDictModule` when `return_log_prob=True`. 
The primary motivation is so that sample_log_prob is returned as part of the tuple of tensors when a probabilistic module is used with tensor arguments via the dispatch decorator (cf. #345)
=> [BugFix] Add sample_log_prob to out_keys when return_log_prob=True

tensordict/nn/common.py, test/test_nn.py
Implements a `select_out_keys` method for all TensorDictModuleBase subclasses, as an alternative to #349 
```
>>> from tensordict.nn import TensorDictModule, TensorDictSequential
>>> mod = TensorDictModule(lambda x, y: (x+2, y+2), in_keys=["a", "b"], out_keys=["c", "d"])
>>> mod(TensorDict({"a": torch.zeros(()), "b": torch.zeros(())}, []))
TensorDict(
fields={
a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
c: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
batch_size=torch.Size([]),
device=None, …
```
=> [Feature] select_out_keys

tensordict/tensordict.py
We call `to(..., non_blocking=True)` in TD creation to make things faster
Before
```python
%%timeit
td = TensorDict({s: torch.zeros(100, 100) for s in string.ascii_lowercase}, [], device="cuda:0")
```
1.16 ms ± 279 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
After
783 µs ± 167 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
Conversely, before:
```python
%%timeit
td = TensorDict({s: torch.zeros(100, 100, device="cuda:0") for s in string.ascii_lowercase}, [], device="cpu")
```
1.25 ms ± 170 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
after
613 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
For the record:
I tested pin_memory but it does not help
=> [Refactor] Faster creation on device

tensordict/nn/common.py, test/test_nn.py
getitem is not working correctly paired with select_out_keys as the input is not a tuple but a list:
```python
mod = TensorDictModule(
lambda x, y: (x + 2, y + 2, x), in_keys=["a", "b"], out_keys=["c", "d", "e"]
)
print(mod.out_keys)
mod.select_out_keys(["c", "d", "e"])
print(mod.out_keys)
mod.reset_out_keys()
print(mod.out_keys)
```
Results in:
```
['c', 'd', 'e']
[['c', 'd', 'e']]
['c', 'd', 'e']
```
then when dispatched [this](https://github.com/pytorch-labs/tensordict/blob/main/tensordict/nn/common.py#L271) raises
=> [Bugfix] fix getitem

tensordict/tensordict.py
`TensorDictBase.masked_select()` will stuck in infinite loop if the input argument `mask` has `.ndimension()` > `self.batch_dims`.
It's obvious to know the bug cause from the code piece below inside the `TensorDictBase.masked_select()` without test, where we see the variables are always not updated in the while condition.
```python
for key, value in self.items():
while mask.ndimension() > self.batch_dims:
mask_expand = mask.squeeze(-1)
else:
mask_expand = mask
value_select = value[mask_expand]
d[key] = value_select
```
```python
from torchrl.envs.libs.gym import GymEnv
from torchrl.collectors import SyncDataCollector, RandomPolicy
import torch
coll=SyncDataCollector(GymEnv("Pendulum-v1"), policy=None, …
```
=> [BugFix] fix infinite loop

tensordict/persistent.py, tensordict/tensordict.py, tensordict/utils.py, test/test_tensordict.py
=> [Feature] Unravel nested keys

tensordict/tensordict.py, test/test_tensordict.py
Note: prints of nested lazy stacks is broken
=> [BugFix] Fix het lazy stack ops

tensordict/tensordict.py
Duplicate after correction of #461 
This is bc-breaking: see #461 for edge cases where membership of lazy stacks fails to be apparent.
Lazy stacks `pop` method now also truly delete the key from the sub-tds, not only hides it (which would make the key reappear anytime valid_keys is recomputed).
=> [Refactor] Better key membership check

benchmarks/common/common_ops_test.py, tensordict/tensorclass.py, tensordict/tensordict.py, test/test_tensordict.py
=> [BugFix] Fix unbind

tensordict/nn/common.py, test/test_nn.py
This allows us to call `reset_parameters()` on a `TensorDictModuleBase` like one would with an `nn.Module`. cc @vmoens or @matteobettini
I am trying to implement ensembles in TorchRL (https://github.com/pytorch/rl/issues/1344) and being able to call `reset_parameters` would make things easier. An added bonus is that now you can reinitialize the parameters for any `TensorDictModule` which seems like it could be handy.
- [ oops ] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)
=> [Feature] Add reset_parameters support to TensorDictModuleBase

tensordict/nn/common.py, test/test_nn.py
This adds support for `TensorDictModuleBase.reset_parameters` when the parameters exist as in a tensordict, rather than being attached to the module. It also simplifies the existing `reset_parameters` implementation. cc @matteobettini @vmoens 
Related to https://github.com/pytorch-labs/tensordict/pull/476 and https://github.com/pytorch/rl/issues/1344
- [ :( ] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)
=> Functional reset_parameters

docs/source/reference/nn.rst, tensordict/nn/__init__.py, tensordict/nn/ensemble.py, test/test_nn.py
This enables the use of functional ensembles in tensordict. I'm having trouble building the docs, but I'm not doing anything crazy with the docs so it should "just work".
I moved https://github.com/pytorch/rl/pull/1359 to the tensordict repo as it could be useful outside of RL scenarios. This makes progress on https://github.com/pytorch/rl/issues/1344.
=> [Feature] Add EnsembleModule

docs/source/reference/nn.rst, tensordict/__init__.py, tensordict/nn/__init__.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensordict.py, test/_utils_internal.py, test/test_nn.py, test/test_tensordict.py
Solves #498 
Aims at solving https://github.com/pytorch/rl/issues/1407
cc @albertbou92 @btx0424
TODO:
=> [Feature] TensorDictParams

tensordict/nn/params.py, tensordict/nn/utils.py, test/test_nn.py
Introduces 2 features for TensorDictParams:
- `pre_get_hooks` allow users to register operations to be executed every time a `get` operation is executed (incl. values, items, `__getitem__`, `get`, `_get_str`, `_get_tuple`). For instance, this allows to create an instance of TensorDictParams that gets the `.data` attribute of another one while keeping the content similar after casting to device or dtype.
- Introduces a `Buffer` class, similar to `nn.Parameter` but without gradient by default. If a tensor is not a parameter in TensorDictParam, it will be a `Buffer`. This change allows us to call `TensorDictParams.to(...)` while being sure that every leaf of the structure has the same identity before and after the operation, as well as the buffers in `_buffers`. Not using this class would …
=> [Feature] Hooks and Buffers for TensorDictParams

tensordict/__init__.py, tensordict/_pytree.py, tensordict/nn/functional_modules.py, test/test_functorch.py, test/test_tensordict.py
Makes tensordict compatible with pytree.
Solves the conflict with vmap between custom _add_batch_dims and torch version. 
We ignore the tensordict node in pytree within vmap and rely on TensorDict._add_batch_dims instead.
cc @NicolasHug @ezyang @zou3519
=> [Feature] PyTree compatibility

tensordict/tensordict.py, test/test_tensordict.py
The following was broken
```
def test_all_keys(self):
td = TensorDict({"a": torch.zeros(1)}, [])
td2 = TensorDict({"a": torch.zeros(2)}, [])
stack = torch.stack([td, td2])
assert set(stack.keys(True, True)) == {"a"}
```
=> [BugFix] Retrieve all keys for `LazyStackedTensorDict`

tensordict/nn/distributions/continuous.py, test/test_nn.py
For continuous action spaces, it is not uncommon to define normal policies with state independent variance. For example, the original PPO paper does so for the MuJoCo trainings. 
This PR proposes o add a module that handles this situation. 
=> [Feature] Module to add state independent normal scale

tensordict/tensordict.py, test/test_tensorclass.py
Closes #511 by making LazyStackedTD.to() return a lazy stack, not a regular td.
Also creates a new test class for tensorclass that assesses that regular ops return an object of the same class (even if they're nested).
=> [BugFix] Fix lazy-stack to call to to_tensordict()

tensordict/memmap.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensordict.py, tensordict/utils.py, test/_utils_internal.py, test/test_memmap.py, test/test_tensorclass.py, test/test_tensordict.py
Refactors the `TensorDict.to` to match more closely `torch.Tensor` and `torch.nn.Module`
This is bc-breaking as previously a single `dest` argument was accepted. Keyword arguments can now be used to map `device`, `dtype`, change the `batch_size`. An example `tensor` / tensordict (`other=...`) can be used to retrieve device and dtype.
=> [Refactor] TensorDict.to() signature

tensordict/tensordict.py, test/test_tensordict.py
- Ensures that empty tensordicts are created for parameter-free modules (eg., nn.Tanh)
- Add a `as_module` arg that allows to get `TensorDIctParams` object that can be used for functional calls as well as storing params in a nn.Module.
=> [Refactor] Refactor  to create empty tds where necessary

tensordict/nn/params.py, tensordict/tensordict.py, tensordict/utils.py, test/test_tensordict.py
WIP to make TensorDict compatible with FCD.
Example usage:
```python
import torch
from functorch import dim
t = torch.randn(3, 4, 5)
td = TensorDict({"t": t}, [3, 4])
d0, d1 = dim.dims(2)
std = td[d0]
print('[d0]', std)
std = td[d0, d1]
print('[d0, d1]', std)
std = td[:, d1]
print('[:, d1]', std)
```
This can be used with modules to batch operations across sets of parameters seamlessly. We extract the parameters, 
```
from torch import nn
net = nn.Sequential(
nn.Linear(3, 4),
nn.Tanh(),
nn.Linear(4, 4),
)
params = TensorDict.from_module(net)
params = params.expand(10).clone()  # a TensorDict of shape [10]
d0 = dim.dims(1)
params = params[d0]
params.to_module(net)  # replace the params
y = net(torch.randn(11, 3))
print(y)
```
`to_module` is a draft of what …
=> [Feature] First class dim compatibility

tensordict/memmap.py, tensordict/tensordict.py, test/test_memmap.py, test/test_tensordict.py
Masks in `torch.where` for lazy stacks need to have as many dims as the tensordict to be unbound along the stack dim. This PR makes sure that it's the case.
=> [BugFix] `torch.where`: Expand mask on the right in lazy stack tds

tensordict/tensordict.py
The memmap_like function does not use `_set_str`, therefore a `to(...)` can be called on memmap tensors, leading them to be regular tensors.
This PR solves this issue
=> [BugFix] Better tensor allocation in memmap_like

tensordict/memmap.py, tensordict/persistent.py, tensordict/tensordict.py
The `device` property of `MemmapTensor` is defined via the method
```python
@property
def device(self) -> torch.device:
return self._device
```
which indicates that the `_device` attribute should only have the `torch.device` type, whereas the current implementation allows assigning a `str` value via the `_init_shape(self, device, ...)` method, which has a parameter `device` typed as `str | Device`.
This change fixes that by simply changing the assignment `self._device = device` in `_init_shape(self, device, ...)` to `self._device = torch.device(device)`. 
When loading a memory mapped tensordict via `td = TensorDict.load_memmap(...)`, the `_device` attribute could be assigned a `str` value. 
This causes `td["some_key"].as_tensor()` to raise `AttributeError` when reading the attribute …
=> Fix assignment of `str`-typed value to `_device` attribute in `MemmapTensor`

tensordict/tensordict.py, test/test_tensordict.py
Refactors split to use slices, to make sure the storage is kept consistent when using map with regular memmap tensors
=> [Refactor] Refactor split

tensordict/_td.py
Older pytorch versions lack the `_global_parameter_registration_hooks` function.
This PR makes it accessory.
=> [BugFix] Compatibility with missing _global_parameter_registration_hooks

tensordict/base.py, tensordict/memmap.py, tensordict/utils.py, test/test_tensordict.py
Seeds the workers in TensorDict.map pool.
The base seed can be passed to the method.
If no seed is required, the unseeded pool can be passed to the method.
The seed is aimed at having a separate seed for each worker and NOT to have reproducible results. By nature, pool's workers will pick up job on the basis of their status, hence the process is non-deterministic by nature.
The tests only verify that with torch and numpy, each worker has a predictable behaviour if the number of jobs equates the number of workers.
cc @NicolasHug
=> [Feature] Seed workers in TensorDict.map

tensordict/nn/common.py, test/test_nn.py
Currently, `TensorDictModule.__getattr__` falls back on the module `__getattr__` if the attribute cannot be found. For `deepcopy`, this causes `__deepcopy__` to return the module within, not the TDModule container copy.
We solve this by excluding any private attribute from fallback.
Related issue:
https://github.com/pytorch/rl/issues/1576#issuecomment-1826899930
=> [BugFix] No fallback on `TensorDictModule.__getattr__` for private attributes

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, test/test_tensordict.py
Allows the following usages of `apply`:
```python
td = TensorDict({"1": 1}, [])
other = TensorDict({}, [])
td.apply(lambda x, y: x+y, other, default=2) # fills "1" with 3
td.named_apply(lambda name, x: x + int(name)) # fills "1" with 2
```
=> [Feature] named_apply and default value in apply

tensordict/_td.py
=> [Performance] Make copy_ a no-op if tensors are identical

tensordict/_td.py, tensordict/memmap.py, tensordict/tensorclass.py, test/test_tensorclass.py
A simple script to test the feature
```python
import tempfile
from tensordict import tensorclass, TensorDict
import torch
import os
def print_directory_tree(path, indent=""):
"""
Print the directory tree starting from the specified path.
Parameters:
- path (str): The path of the directory to print.
- indent (str): The current indentation level for formatting.
"""
if os.path.isdir(path):
print(indent + os.path.basename(path) + "/")
indent += "    "
for item in os.listdir(path):
print_directory_tree(os.path.join(path, item), indent)
else:
print(indent + os.path.basename(path))
@tensorclass
class MyClass:
X: torch.Tensor
td: TensorDict
integer: int
string: str
dictionary: dict
@tensorclass
class MyOtherClass:
Y: torch.Tensor
data = MyClass(
X = torch.randn(10, 3),
td=TensorDict({"y": …
```
=> [Feature] Saving metadata of tensorclass

tensordict/memmap.py, test/_utils_internal.py
=> [BugFix] Fix osx tests

tensordict/_lazy.py, tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/memmap.py, tensordict/memmap_deprec.py, tensordict/nn/common.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/_utils_internal.py, test/test_tensorclass.py, test/test_tensordict.py
The only bit remaining with this API is a proper interaction with elements in a state_dict that are not tensors. 
We just need to detect if an item is or isn't a tensor and if not call `set_non_tensor`. At load time, loading from the `memmap` file structure is already coded, the only thing will be to make sure that the `load_state_dict` hooks are compatible with this. GIven that this is a slightly different track than the core functionality proposed by this PR, I will make this in a separate one.
@fegin
=> [Feature] Storing non-tensor data in tensordicts

tensordict/_lazy.py, tensordict/_torch_func.py, test/test_tensordict.py
Allows torch.stack to return a TensorDict whenever possible, and a LazyStackedTensorDict otherwise.
This is aimed at simplifying stacking tensordicts together while preserving the features of LazyStackedTDs.
Currently, this behaviour is only enabled when `set_lazy_legacy(False)` is called. In the future, `lazy_legacy()` will be `False` by default making this behaviour the default in tensordict.
In the PyTorch PR, this will be the only accepted behaviour of `torch.stack`.
cc @shagunsodhani  @matteobettini
=> [Feature] Best intention stack

docs/source/index.rst, docs/source/reference/index.rst, docs/source/reference/tensorclass.rst, docs/source/reference/tensordict.rst, docs/source/saving.rst, tensordict/memmap_deprec.py, tensordict/utils.py
=> [Doc] Doc revamp

tensordict/__init__.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, test/test_nn.py, test/test_tensordict.py
Makes it possible to call `zero_` and such on TensorDictParams, and makes these ops active on the data.
Also clarifies the docstring of `clone`
=> [Feature] Improve in-place ops for TensorDictParams

tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, test/test_nn.py
Allows `to_module` to write tensors in-place.
=> [Feature] inplace to_module

.pre-commit-config.yaml, tensordict/_lazy.py, tensordict/base.py, test/test_distributed.py
I add an optional keyword argument `group` for all communication-related methods.
Close #615.
=> [Feature] Support group specification

tensordict/base.py
=> [Performance] Faster set

benchmarks/distributed/distributed_benchmark_test.py, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/utils.py, test/test_tensordict.py
I'm grouping #620 and this PR.
The pitch is that we used to have a `_is_memmap` and `_is_shared` args in the tensordict constructor, but that is messy: is_shared() should only be true when the tensordict is locked, but when a td was created from another one the locked attribute wasn't passed whereas the shared attributee was.
To solve this, we will make sure that ops that are not modifying the tensors pass explicitly the shared and locked attributes.
I take the opportunity of the refactoring to make `exclude` faster.
=> [Performance] Better shared/memmap inheritance and faster exclude

tensordict/_td.py, tensordict/base.py, test/test_tensordict.py
@shagunsodhani I may benefit from a bit of feedback on this.
When a tensordict is placed in shared memory or memmaped, it is blocked. We do this to avoid having people writing in it and hoping that these changes will be reflected in another process (which won't be the case). Locking the tensordict ensures that you must first unlock it (and hence loose the `is_shared()` attribute) before writing. 
For some operations (typically all the ops that don't change the `data_ptr()` ) I thought it was cool to keep the `is_shared()` attribute since we can be sure that the content is still shared. That means that coming from a shared / memmap tensordict all these ops would return a shared and locked tensordict:
```python
td.view(-1)
td.transpose(0, 1)
td.select("key")
td.exclude("key") …
```
=> [BugFix] Remove shared/memmap inheritance from clone / select / exclude

tensordict/nn/common.py, tensordict/nn/ensemble.py, tensordict/nn/probabilistic.py, tensordict/nn/sequence.py, tensordict/nn/utils.py, test/test_nn.py
This PR prepares the deprecation of the previous functional API and makes it possible to ignore the `@dispatch` decorator
=> [Feature] _auto_make_functional and _dispatch_td_nn_modules

tensordict/_lazy.py, tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/nn/ensemble.py, tensordict/utils.py, test/_utils_internal.py, test/test_functorch.py, test/test_tensorclass.py, test/test_tensordict.py, tutorials/sphinx_tuto/tensordict_shapes.py
Soon we will make all ops non-lazy by default (for v0.3)
I expect this to be bc-breaking for some users, but most should not be impacted. In fact, life will be much easier (a lot of `.contiguous()` calls  will be unnecessary).
The plan is to keep `LazyStackedTensorDict` there, as it's a useful abstraction to carry heterogeneous data structures or whenever one does not want to stack all the tensors of a data source.
In this PR, I set the lazy_legacy to False and test if all the tests pass. The plan it to reset it to True before merging, in such a way that we're sure that this PR does not break everything in torchrl for instance.
The plan for `torch.stack` is that we'll be looking at the lazy_legacy env variable for 1 release:
- if None, then the user has not said if she wanted a lazy …
=> [Feature] Robust to lazy_legacy set to false and context managers for reshape ops

tensordict/_td.py, tensordict/base.py, test/test_tensordict.py
Closes https://github.com/pytorch/rl/issues/1593
=> [BugFix] Loading phantom state-dicts

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/tensorclass.py, test/test_tensordict.py
Using apply to filter data returns an empty tensordict, but one could expect to receive nothing at all if the operation doesn't return anything.
This PR solves this issue.
=> [BugFix,Feature] filter_empty in apply

tensordict/base.py, tensordict/utils.py, test/test_tensordict.py
Allows calls to map to receive a preallocated output where the results should be stored. 
Another util will be provided to construct this preallocated output on the fly (without custom code).
Example:
```python
import torch
import tempfile
from  pathlib import Path
def fn(input):
return input.select("a")
if __name__ == "__main__":
for mmap in [True, False]:
for chunksize in [0, 2]:
with tempfile.TemporaryDirectory() as tmpdir:
tmpdir = Path(tmpdir)
input = TensorDict(
{"a": torch.arange(10), "b": torch.arange(10)},
[10]
)
if mmap:
input.memmap_(tmpdir / "input")
out = TensorDict(
{"a": torch.zeros(10, dtype=torch.int)},
[10]
)
if mmap:
out.memmap_(tmpdir / "output")
input.map(fn, num_workers=2, chunksize=chunksize, out=out)
assert (out["a"] == …
```
=> [Feature] map with preallocated output

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, test/test_nn.py
This is a quick fix for to_module runspeed until we find a better way of doing this.
cc @matteobettini
=> [BugFix] Faster to_module

tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
=> [Feature] `from_modules` method for MOE / ensemble learning

tensordict/_td.py, test/test_nn.py
Closes https://github.com/pytorch/rl/issues/1957
=> [BugFix] Fix to_module batch-size mismatch

tensordict/nn/params.py, test/test_nn.py
Closes https://github.com/pytorch/rl/issues/1960
=> [BugFix] Fix load_state_dict for TensorDictParams

tensordict/nn/common.py, test/test_nn.py
Related to https://github.com/pytorch/rl/issues/1967
=> [Feature] Warn when `reset_parameters_recursive` is a no-op

docs/source/reference/tensorclass.rst, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
Nested tensorclasses will need some form of autocasting to make sure that a dict within a dict is interpreted as the right class. 
The PR also proposes such auto-casting for tensor containers only (leaves are not auto-cast, as it is the case with tensordict).
The doc has been updated to account for this feature, and tests have been written for it too.
cc @maximilianigl
=> [BugFix, Feature] tensorclass.to_dict and from_dict

tensordict/_torch_func.py
=> [BugFix] Dense stack lazy tds defaults to dense_stack_tds

README.md, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, test/test_tensordict.py
cc @Cadene: I made more explicit the doc RE dict compatibility in the readme. I will update the doc separately. Feedback is welcome!
cc @Miffyli I also made a `save`, `dump` and `load` function to make sure people are not-so-scared about memory-mapped tensors :p
=> [Feature] __contains__, clear and fromkeys

tensordict/base.py, test/test_tensordict.py
cc @cpuhrsch
cc @ahmed-touati: once this lands, you will be able to speed up split-trajectories using this
```python
split_trajectories(sample, as_nested=True).to_padded_tensor()
```
which brings a 2.5x speed-up in my benchmarks
=> [Feature] tensordict.to_padded_tensor

README.md, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/csrc/utils.h, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensordict.py
Test the feature:
```python
from torch.nn import Transformer
import torch
from torch.utils.benchmark import Timer
t = Transformer(device="cuda" if torch.cuda.is_available() else "cpu")
params = TensorDict.from_module(t).apply(lambda t: t.data.clone().fill_(0.0))
other_params = TensorDict.from_module(t).apply(lambda t: t.data.clone().fill_(1.0))
assert (params.add(other_params) == 1).all()
print("\n\nadd")
params.add(other_params)
print("foreach", Timer("params.add(other_params)", globals=globals()).adaptive_autorange())
params.lock_()
other_params.lock_()
params.add(other_params)
print("foreach, locked", Timer("params.add(other_params)", globals=globals()).adaptive_autorange())
params.apply(lambda x, y: x+y, other_params)
print("apply", …
```
=> [Feature] Pointwise arithmetic operations using foreach

docs/source/overview.rst
Two commas are missed in the documentation/overview (see screenshots below)
=> [Doc] fix typo

tensordict/_td.py, tensordict/base.py, tensordict/utils.py
This is a proposal for speedup improvements for TensorDict struct by adding fast path for common use cases.
I only tested test/test_tensordict.py locally (the subset that works on main), there is most likely a few things I missed!
Runtime is tested with
```python
from torch.nn import Transformer
import torch.utils.benchmark
t = Transformer()
td = TensorDict.from_module(t)
print(torch.utils.benchmark.Timer("td.flatten_keys()", globals=globals()).adaptive_autorange())
td.lock_()
print(torch.utils.benchmark.Timer("td.flatten_keys()", globals=globals()).adaptive_autorange())
print(torch.utils.benchmark.Timer("""td.flatten_keys(".")""", globals=globals()).adaptive_autorange())
```
Result before:
```
<torch.utils.benchmark.utils.common.Measurement object at …
```
=> [Performance] Random speedups

tensordict/functional.py, test/test_tensordict.py
This PR augments the ```pad_sequence``` function by allowing the parameter ```return _mask``` to be either a ```bool ``` or ```str```. In case ```return_mask``` is a ```bool```, the function behaves as before, but if ```return_mask``` is a ```str```, then the provided string becomes the key for the padding masks instead of "masks".
Additionally, for debugging purposes, if the TensorDict contains scalar tensors i.e. ```torch.Size([])```, the function raises a runtime error that the method does not support padding scalar tensors. This is consistent with ```torch.nn.utils.rnn.pad_sequence```. In case, we would like to support this we could just unqueeze such tensors. 
In case the user already has some masks within the TensorDict under a key "masks" this will prevent the issue of renaming the …
=> [Feature] use return_mask as a string in pad_sequence  

.github/scripts/m1_script.sh, .github/workflows/wheels.yml, setup.py
Closing https://github.com/pytorch/rl/issues/2124
=> [Versioning] Allow any torch version for local builds

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
Allows to load (asynchronously) a tensordict on device, or on "meta" (ie creating a meta-tensordict without reading any data except metadata)
Test the feature:
```python
import tempfile
from tensordict import TensorDict, is_tensor_collection
from torch.nn import Transformer
import torch
with tempfile.TemporaryDirectory() as tmpdir:
t = Transformer(
d_model=64, nhead=4, num_encoder_layers=3, dim_feedforward=128
)
state_dict = TensorDict.from_module(t)
state_dict.data.zero_()
state_dict.save(tmpdir)
meta_state_dict = TensorDict.load(tmpdir, device="meta")
def check_meta(tensor):
assert tensor.device == torch.device("meta")
meta_state_dict.apply(check_meta, filter_empty=True)
if torch.cuda.is_available():
device = "cuda:0"
elif torch.backends.mps.is_available():
device = "mps:0" …
```
=> [Feature] Load tensordicts on device, incl. meta

tensordict/memmap.py, test/test_memmap.py
Unfortunately I didn't manage to find a way to make the error more explicit if the file is being written when it isn't writable (currently this will raise a segfault).
Also the workaround I found doesn't give you a storage with a filename associated - it's a bit hacky from that point of view. MemoryMappedTensor will have its filename attribute set however. See tests for more context
cc @albanD, @MateuszGuzek @mikaylagawarecki
=> [BugFix] Read-only compatibility in MemoryMappedTensor

tensordict/memmap.py, test/test_memmap.py
Currently _is_writable check if any user or group can write to file. In practice, we want to chek if active user can do that. The simple fix should solve the issue, I tested it locally on a problematic file where owner could write to but group not. With the proposed changes, it works.
=> [BugFix] Check if the current user has write access

tensordict/base.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Feature] TensorDict.numpy()

tensordict/_lazy.py, tensordict/_pytree.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/functional.py, tensordict/nn/functional_modules.py, tensordict/tensorclass.py, test/test_functorch.py, test/test_tensordict.py
The goal of this PR is that stacking 2 identical (in structure) lazy stacks, the resulting tensordict is a lazy stack containing dense tensordicts.
cc @matteobettini @dtsaras
=> [Feature] Best attempt to densly stack sub-tds when LazyStacked TDS are passed to maybe_dense_stack

setup.py, tensordict/base.py, tensordict/nn/distributions/composite.py, tensordict/nn/utils.py, tensordict/utils.py, tutorials/sphinx_tuto/tensorclass_imagenet.py
The current use of deprecated `distutils` is fairly limited and is the last reason for `tensordict` being incompatible with python 3.12.
This PR brings [distutils' implementation of `strtobool`](https://github.com/pypa/distutils/blob/4549de12976703a135c0b9db71e5aaa3ba0f34a6/distutils/util.py#L334) to `tensordict/utils.py`.
Note: Although `distutils` is not anymore required as a runtime dependency and `tensordict` now being compatible with python 3.12, there remains a reference to `distutils.command.clean` in [setup.py](https://github.com/pytorch/tensordict/blob/7e8cba9b2e620471132cd3184f5458d1ffb91009/setup.py#L85-L99).
You can use the syntax `close #15213` if this solves the …
=> [Feature] remove distutils dependency and enable 3.12 support

tensordict/_td.py, tensordict/_torch_func.py, tensordict/memmap.py, test/test_memmap.py
However, this fails on our tests
For a minimal reprod https://gist.github.com/vmoens/83cdb5b9059e319829607c22927f0383
cc @teopir @albanD @mikaylagawarecki
=> [Refactor] use from_file instead of mmap+from_buffer for readonly files

tensordict/tensorclass.py, test/test_tensorclass.py
=> [BugFix] @property setter in tensorclass

tensordict/base.py
Benchmark:
```python
import time
from matplotlib import pyplot as plt
def makelockunlock(n, lock_only=True):
prev_td = None
for i in range(n):
td = TensorDict()
if prev_td is not None:
td["nested"] = prev_td.lock_()
prev_td = td
if lock_only:
t0 = time.time()
td.lock_()
return time.time()-t0
else:
t0 = time.time()
td.lock_().unlock_()
return time.time()-t0
ts = [min(makelockunlock(i), makelockunlock(i)) for i in range(2, 200)]
plt.plot(ts)
ts = [min(makelockunlock(i, False), makelockunlock(i, False)) for i in range(2, 200)]
plt.plot(ts)
```
Before:
After:
=> [Performance] Faster lock_/unclock_ when sub-tds are already locked

tensordict/nn/common.py, test/test_nn.py
=> [BugFix] FIx non-tensor writing in modules

tensordict/nn/distributions/continuous.py, tensordict/nn/distributions/discrete.py, tensordict/nn/probabilistic.py
=> [Feature] DETERMINISTIC interaction mode

tensordict/nn/probabilistic.py
=> [BugFix] Fix fallback of deterministic samples when mean is not available

tensordict/base.py, tensordict/utils.py, test/test_tensordict.py
=> [Feature] from and to_pytree

tensordict/base.py, tensordict/utils.py
=> [Feature] Better dtype coverage

tensordict/_lazy.py, tensordict/tensorclass.py, test/test_tensordict.py
=> [BugFix] Avoid collapsing NonTensorStack when calling where

.pre-commit-config.yaml, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensorclass.py, test/test_tensordict.py
multithreaded apply should only be used internally as there is a non-negligeable set of operations that can lead to deadlocks. 
As of now, it is __not__ made to speed up the tensordict operations (reduce TD overhead) but speed up the execution of any function passed to `apply` that can benefit from being executed asynchronously over the leaves.
Some benchmarks:
```python
import torch
from torch.utils.benchmark import Timer
import functools
d = {}
sub = d
for _ in range(20):
for i in range(50):
sub[str(i)] = torch.rand(2048, 2048)
sub["nested"] = {}
sub = sub["nested"]
td = TensorDict(d, batch_size=[])
assert (td._multithread_apply_nest(lambda x: x, num_threads=16) == td).all()
func = lambda x: x.pin_memory()
print(Timer("td._fast_apply(func)", …
```
=> [Feature] Multithreaded apply

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/utils.py, test/test_tensordict.py
Test:
```python
import torch
from torch.utils.benchmark import Timer
import functools
d = {}
sub = d
for _ in range(20):
for i in range(50):
sub[str(i)] = torch.rand(2048, 2048)
sub["nested"] = {}
sub = sub["nested"]
td = TensorDict(d, batch_size=[])
print(Timer("td.to('cuda')", globals=globals()).adaptive_autorange())
Median: 1.02 s
print(Timer("td.pin_memmory().to('cuda')", globals=globals()).adaptive_autorange())
print(Timer("td.to('cuda', pin_memory=True)", globals=globals()).adaptive_autorange())
print(Timer("td.to('cuda', pin_memory=True, num_threads=0)", globals=globals()).adaptive_autorange())
print(Timer("td.to('cuda', pin_memory=True, num_threads=1)", globals=globals()).adaptive_autorange())
print(Timer("td.to('cuda', pin_memory=True, …
```
=> [Feature,Performance] `to(device, pin_memory, num_threads)`

tensordict/_td.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
This is bc-breaking in the following ways:
1. non-tensor data are proper leaves in the tensorclass
```python
data = MyData(X=X, y=y, z="a string", batch_size=batch_size)
assert "z" in data.keys() # used to break
```
2. non-tensor data will be compared if a tensorclass is compared to another tc / td
```python
z = "a striing!"
tensordict = TensorDict(
{
"X": X,
"y": y,
},
batch_size=[3, 4],
)
data = MyData(X=X, y=y, z=z, batch_size=batch_size)
assert (tensordict == data).all()
tensordict = TensorDict(
{
"X": X,
"y": y,
},
batch_size=[3, 4],
)
```
3. Non-tensor data following comparison is not None
```python
data0 = MyData(X=X, y=y, z="a string", batch_size=batch_size)
data1 = MyData(X=X, y=y, z="another string", batch_size=batch_size)
(data0 == data1).z # used to be None, now a TD with …
```
=> [Refactor] Make all leaves in tensorclass part of `_tensordict`, except for NonTensorData

test/test_memmap.py
Interestingly apply silicon runners are the only machines that don't have root permission in the CI, and hence are the only one that run the `TestReadWrite` test.
All file-stored storages used to have a `filename` associated but we deprecated this since there was not guarantee that a change in a non-writable file would be reflected on the corresponding opened tensor (making the filename useless and misleading).
This PR fixes that test.
cc @mikaylagawarecki
=> [BugFix,CI] Fix storage filename tests

tensordict/tensorclass.py, test/test_tensordict.py
=> [BugFix] Fix setting non-tensors as data in NonTensorData

.github/unittest/linux/scripts/run_test.sh, .github/unittest/linux_torchrec/scripts/run_test.sh, .github/unittest/rl_linux_optdeps/scripts/run_test.sh, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/common.py, tensordict/nn/params.py, tensordict/nn/sequence.py, tensordict/nn/utils.py, tensordict/utils.py, test/test_compile.py
=> [Feature] Compile - nn compatibility

tensordict/_lazy.py, tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/nn/common.py, tensordict/nn/probabilistic.py, tensordict/persistent.py, tensordict/prototype/fx.py, tensordict/tensorclass.py, tensordict/utils.py
=> [Quality] zip-strict when possible

tensordict/_contextlib.py, tensordict/_lazy.py, tensordict/_pytree.py, tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/functional.py, tensordict/nn/common.py, tensordict/nn/functional_modules.py, tensordict/nn/params.py, tensordict/nn/probabilistic.py, tensordict/nn/sequence.py, tensordict/nn/utils.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_compile.py, test/test_tensorclass.py
=> [Feature] Compile - tensorclass compatibility

.github/workflows/benchmarks.yml, .github/workflows/benchmarks_pr.yml, benchmarks/compile/compile_td_test.py, benchmarks/compile/tensordict_nn_test.py, benchmarks/tensorclass/test_torch_functions.py
=> [Feature] Compile - benchmarks

tensordict/functional.py, test/test_tensordict.py
Fix the way `pad_sequence` checks for non-tensor attributes of tensorclasses. Also raise an error if `pad_sequence` is given tensorclasses with `return_mask=True`, since we cannot add the "masks" attribute with `<tensorclass>.set()`.
close #783
=> [BugFix] Fix `pad_sequence` behavior for non-tensor attributes of tensorclass

tensordict/_td.py, test/test_tensordict.py
=> [Feature] construct tds with kwargs

tensordict/_td.py, tensordict/base.py, tensordict/persistent.py, test/test_tensordict.py
=> [Feature] flatten_keys and unflatten_keys as context managers

tensordict/nn/__init__.py, tensordict/nn/distributions/continuous.py, tensordict/nn/utils.py
- Adds a `add_custom_mapping` for the `mappings` function
- moves the `mappings` dict outside of the function to reduce overhead
- documents the NPW deprecation
- Adds the `"none"` option in the mappings to allow for no transformation to occur.
=> [Feature] add_custom_mapping and NPE refactors

tensordict/nn/functional_modules.py, tensordict/tensorclass.py, test/test_compile.py
When calling a vmap within a compiled code, things break because of the context manager that we use to exclude TDs from pytree.
We can actually just indicate that TD is a leaf using the `is_leaf` argument where appropriate.
This will only work with torch > 2.4.
=> [BugFix] Fix compile + vmap

tensordict/base.py, tutorials/dummy.py, tutorials/sphinx_tuto/tensorclass_fashion.py, tutorials/sphinx_tuto/tensorclass_imagenet.py, tutorials/sphinx_tuto/tensordict_memory.py
The only remaining non ascii-characters are in the turorials, which should not be a problem for compiled jobs:
In `tensordict_memory.py`:
```
tensordict
├── a.memmap
├── b
│   ├── c.memmap
│   └── meta.json
└── meta.json
```
=> [Refactor] Remove non-ascii characters from code base

tensordict/base.py, test/test_compile.py
dynamo ctx_manager attempts to print an incomplete version of the object
In this case, the `TensorDict` instance lacks a `_tensordict` and `_batch_size` attribute (which should never be the case in eager mode), and the error that should result from `unimplemented` is never raised because the `__repr__` of the tensordict in `self.cm_obj` never returns.
@anijain2305 in the following code snippet, it could be wise to either print only the type of `self.cm_obj` or decorate this in a `try/except` such that the `__repr__` of self.cm_obj doesn't hide the real error.
```
File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/variables/ctx_manager.py", line 154, in enter
f"Unsupported context manager {self.cm_obj}'s __enter__ function", …
```
=> [BugFix] Fix error catching of context-manager support in compile

tensordict/tensorclass.py, test/test_tensordict.py
=> [Feature] Make NonTensorData a callable

tensordict/_td.py, tensordict/base.py, tensordict/nn/common.py, tensordict/nn/distributions/composite.py, tensordict/nn/functional_modules.py, tensordict/nn/params.py, tensordict/nn/probabilistic.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensordict.py
dict.get defaults to None, but TD.get doesn't.
This PR solves this discrepancy.
Note that this is a BC-breaking change.
=> [Refactor] make TD.get default to None, like dict

tensordict/_lazy.py, tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
=> [Feature] Densify lazy tensordicts

docs/source/index.rst, tutorials/sphinx_tuto/streamed_tensordict.py
=> [Doc] Streaming tensordicts

tensordict/nn/distributions/composite.py
This PR allows to change the output key used for the `sample_log_prob` in `CompositeDistribution`'s, which is now hardcoded to `sample_log_prob`.
=> [Feature] Allow to specify log_prob_key in CompositeDistribution

.github/workflows/benchmarks.yml, .github/workflows/benchmarks_pr.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/nightly_build.yml, .github/workflows/test-linux.yml, .github/workflows/test-rl-gpu.yml, .github/workflows/wheels-windows.yml
=> [CI] Upgrade 3.8 workflows

tensordict/_td.py, tensordict/_torch_func.py, tensordict/utils.py
=> [BugFix] Other dynamo fixes

tensordict/base.py, tensordict/tensorclass.py
=> [Feature] Better typing for tensorclass

tensordict/tensorclass.py, test/test_tensorclass.py
=> [Feature] Frozen tensorclass

tensordict/nn/probabilistic.py
=> [Refactor] Use IntEnum for interaction types

tensordict/_td.py
=> [BugFix] Fix td device sync when error is raised

benchmarks/compile/compile_td_test.py, benchmarks/compile/tensordict_nn_test.py, docs/source/reference/nn.rst, tensordict/nn/__init__.py, tensordict/nn/common.py, tensordict/nn/cudagraphs.py, tensordict/nn/functional_modules.py, test/test_compile.py, test/test_nn.py
Added CudaGraphModule class to provide a user-friendly interface to CUDA graphs for PyTorch callables. 
This class enables fast, CPU-overhead-free execution of operations on GPU while ensuring essential checks for input functions. Includes documentation and example usage.
cc @mikaylagawarecki @albanD @eellison @BoyuanFeng @Chillee
=> [Feature] Cudagraphs

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/persistent.py, test/test_tensordict.py
=> [Feature] sorted keys, values and items

tensordict/nn/cudagraphs.py
=> [BugFix] Fix tree_leaves import for older versions of PT

.github/unittest/linux/scripts/environment.yml, tensordict/_td.py, tensordict/base.py, tensordict/nn/common.py, test/test_compile.py
* #994
* #993
* #992
* __->__ #991
=> [Feature] torch.export and onnx compatibility

test/test_compile.py
=> [Test] Skip compile tests that require 2.5 for stable

tensordict/nn/common.py, test/test_nn.py
=> [Feature] `inplace` arg in TDM constructor

tensordict/_torch_func.py, tensordict/base.py, test/test_tensordict.py
=> [BugFix] Fix number check in array parsing (np>=2 compatibility)

tensordict/nn/distributions/composite.py, tensordict/nn/probabilistic.py
=> [BugFix] Resilient deterministic_sample for CompositeDist

.github/workflows/docs.yml, docs/source/reference/nn.rst, docs/source/reference/tensordict.rst, tensordict/__init__.py
=> [Doc] Fix tutorials

.github/workflows/build-wheels-windows.yml, .github/workflows/wheels-windows.yml, tensordict/base.py
=> [CI] Fix windows wheels

tensordict/nn/functional_modules.py
=> [BugFix] Fix vmap monkey patching

tensordict/nn/cudagraphs.py
=> [BugFix] Use separate streams for cudagraph warmup

tensordict/base.py, test/test_tensordict.py
=> [Feature] cat_tensors and stack_tensors

tensordict/base.py, test/test_tensordict.py
=> [Feature] cat and stack_from_tensordict

tensordict/base.py, test/test_tensordict.py
=> [Feature] TensorDict.record_stream

tensordict/_reductions.py, test/test_tensorclass.py, test/test_tensordict.py
* #1023
* #1022
* #1021
* #1020
* __->__ #1019
=> [BugFix] Deserializing a consolidated TD reproduces a consolidated TD

tensordict/nn/distributions/continuous.py
=> [Refactor] better AddStateIndependentNormalScale

tensordict/_reductions.py, tensordict/base.py, tensordict/utils.py, test/test_tensordict.py
* #1023
* #1022
* __->__ #1021
=> [Feature] NJT with lengths

tensordict/base.py
=> [Feature] _foreach_copy_ for update_

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/functional.py, tensordict/nn/__init__.py, tensordict/nn/common.py, tensordict/nn/probabilistic.py, tensordict/nn/utils.py, tensordict/utils.py
=> [Deprecation] Act warned deprecations for v0.6

tensordict/base.py
=> [BugFix] Fix _foreach_copy_ for older versions of PT

tensordict/nn/cudagraphs.py, test/test_compile.py
=> [BugFix] Compatibility with non-tensor inputs in CudaGraphModule

tensordict/tensorclass.py
```python
@tensorclass() # works without typing issues
class MyClass:
a = torch.Tensor
b = torch.Tensor
@tensorclass # results in pyright typing issues and is arguably more commonly used than @tensorclass() with parentheses
class MyClass:
a = torch.Tensor
b = torch.Tensor
```
pyright: error:
```
Argument of type "type[MyClass]" cannot be assigned to parameter "autocast" of type "bool" in function "__new__"
"type[type]" is not assignable to "type[bool]"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```
I looked at the `@dataclass` implementation and mimicked the behavior here. I'm no expert in typing.
- typing change
Potential breaking change:
Technically you could have used @tensordict …
=> [Refactor] Make @tensorclass work properly with pyright

benchmarks/common/h2d_test.py, benchmarks/compile/compile_td_test.py, benchmarks/compile/tensordict_nn_test.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/cudagraphs.py, tensordict/utils.py, test/test_compile.py, test/test_distributed.py, test/test_tensordict.py
=> [Performance] Faster clone

tensordict/base.py, test/test_tensordict.py
=> [Feature] param_count

tensordict/nn/params.py
=> [BugFix] Fix pre 2.1 _apply compatibility

benchmarks/common/h2d_test.py
=> [CI] Fix versioning of h2d tests

tensordict/_td.py
Resolve the reference cycle introduced by the function `proc_dim`.
close #1055 
=> [BugFix] Reference cycle in TensorDict._cast_reduction

tensordict/base.py
=> [Refactor] Better handling of params and buffers in bytes

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Refactor] Refactor keys, items and values

tensordict/_td.py, tensordict/base.py, tensordict/tensorclass.py, tensordict/utils.py
=> [Performance] Faster _is_tensor_collection in eager mode

tensordict/_td.py, tensordict/utils.py
=> [Minor] Fix wrong fbcode manual links

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/utils.py, test/_utils_internal.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Feature] inplace to method

tensordict/base.py, test/test_tensordict.py
=> [BugFix] Ensure grads and noned when needed

test/test_tensordict.py
=> [BugFix] Fix grad tests

tensordict/_td.py, tensordict/base.py
=> [Performance] Faster to

tensordict/functional.py
Allow `functional.pad` to take a tuple for `pad_size`.
I recently tried to use `pad` with a tuple for `pad_size`, but it didn't work as expected.
Close #1074
- Bug fix (non-breaking change which fixes an issue)
=> [BugFix] calling pad with immutable sequence

tensordict/utils.py, test/test_tensordict.py
=> [BugFix] Better repr of lazy stacks

tensordict/_td.py
=> [Quality] Better error message for incongruent lists of keys

tensordict/_lazy.py, tensordict/_td.py, tensordict/utils.py
=> [Feature] `intersection` for assert_close

tensordict/base.py
=> [Doc] Better docstring for to_module

tensordict/nn/utils.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Refactor] `__eq__` to identity check in non-tensor stacking

tensordict/nn/utils.py
=> [Refactor] Make _set_dispatch_td_nn_modules compatible with compile

tutorials/sphinx_tuto/export.py
=> [Doc] Add doc on export with nested keys

tensordict/utils.py
=> [Minor] print_directory_tree returns a string

tensordict/nn/probabilistic.py
=> [Quality] Better use of StrEnum in set_interaction_type

tensordict/nn/probabilistic.py, test/test_nn.py
=> [BugFix] smarter check in set_interaction_type

tensordict/nn/params.py, tensordict/nn/probabilistic.py, test/test_compile.py
=> [BugFix] inline TDParams kwargs in prob modules

tensordict/nn/probabilistic.py, test/test_compile.py
=> [Test] fix inline TDParams kwargs for nontensordata

docs/source/reference/tensorclass.rst, tensordict/__init__.py, tensordict/_lazy.py, tensordict/_reductions.py, tensordict/_td.py, tensordict/base.py, tensordict/functional.py, tensordict/nn/common.py, tensordict/nn/params.py, tensordict/persistent.py, tensordict/tensorclass.py, tensordict/tensorclass.pyi, tensordict/utils.py, test/_utils_internal.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Feature,Refactor] Refactor from_dict, add from_any, from_dataclass

tensordict/nn/probabilistic.py, tensordict/nn/sequence.py, test/test_nn.py
=> [BugFix] select_out_keys for Prob sequential

docs/source/distributed.rst
Small PR - https://github.com/pytorch/rl/commit/da88aadb24b0cb1a8c0ef5e5140d219b32096e41 moved the location of `distributed_replay_buffer.py`. This PR adjusts sources to changes.
=> [Doc] Update `distributed_replay_buffer.py` reference

tensordict/base.py, test/test_tensordict.py
* #1109
* #1108
* #1107
* __->__ #1106
=> [Feature] from_any with UserDict

tensordict/tensorclass.py, test/test_tensordict.py
* #1109
* #1108
* __->__ #1107
* #1106
=> [Feature] NonTensorStack.from_list

tensordict/base.py, tensordict/nn/common.py, tensordict/utils.py, test/test_tensordict.py
* #1109
* __->__ #1108
* #1107
* #1106
=> [Feature] Better list casting in TensorDict.from_any

tensordict/nn/common.py, test/test_nn.py, test/test_tensordict.py
* __->__ #1109
* #1108
* #1107
* #1106
=> [BugFix] auto-batch-size in dispatch

test/test_tensordict.py
=> [BugFix] Fix from_any tests

tensordict/base.py, tensordict/nn/params.py, tensordict/nn/probabilistic.py, tensordict/nn/utils.py, tensordict/utils.py, test/test_nn.py, test/test_tensordict.py
=> [Refactor] Refactor context managers

test/conftest.py, test/test_tensordict.py, tutorials/sphinx_tuto/export.py, tutorials/sphinx_tuto/tensordict_module.py
=> [BugFix] Use 'spawn' mp context in all tests

tensordict/nn/distributions/composite.py, test/test_nn.py
* #1114
* #1113
* __->__ #1112
In this PR, I propose a new vision for `CompositeDistributions` where in the future:
- log_prob will return a tensordict with log-probs if not asked otherwise
- the aggregate log_prob will not be computed. Users will have the opportunity to do that manually, for instance through 
```python
lp = dist.log_prob(sample, inplace=False)
lp = lp.sum(reduce=False)
```
- the tensordict returned will not be the one used as input but another one.
This implies:
- reverting the announced deprecation (FutureWarning) for `aggregate_probabilities` (cc @albertbou92). The idea is that we actually want `aggregate_probabilities` to be False because we want this class to be an exclusively …
=> [Refactor] Make CompositeDistribution a tensordict-exclusive class

tensordict/nn/distributions/composite.py, test/test_nn.py
* #1114
* __->__ #1113
* #1112
=> [Feature] CompositeDistribution.from_distributions

docs/source/reference/tensordict.rst, tensordict/__init__.py, tensordict/_td.py, tensordict/base.py, tensordict/persistent.py, tensordict/tensorclass.py
=> [Feature,Refactor] More args in constructors, refactor free functions

docs/source/reference/nn.rst, tensordict/nn/__init__.py, tensordict/nn/common.py
* __->__ #1118
* #1117
* #1114
=> [Feature] Expose WrapModule

tensordict/base.py, test/test_tensordict.py
=> [BugFix] Cloning empty tensordicts

tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
=> [Feature] TensorDict.separates

tensordict/nn/probabilistic.py, test/test_nn.py
=> [Feature] ProbabilisticTensorDictSequential.default_interaction_type

tensordict/tensorclass.py
=> [BugFix] Add checks and to_module to tensorclass accepted methods

tensordict/nn/params.py
=> [BugFix] Do not unlock td if it's not locked in TDParams (for compile compat)

tensordict/utils.py, test/smoke_test.py
=> [Versioning] python 3.8 compatibility fix

test/test_nn.py
=> [Tests] Skip deprecation warning tests on FB fbcode

tensordict/_lazy.py, tensordict/base.py, tensordict/tensorclass.pyi, test/smoke_test.py
* #1136
* #1135
* __->__ #1134
=> [Quality] Avoid torch.distributed imports at root

tensordict/_lazy.py, tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/tensorclass.py, tensordict/utils.py
* __->__ #1136
* #1135
* #1134
=> [Refactor] Avoid lambda functions in core functionality

tensordict/_lazy.py, tensordict/base.py, tensordict/tensorclass.py
=> [Feature] NonTensorStack.data

tensordict/nn/distributions/continuous.py, tensordict/nn/distributions/discrete.py, tensordict/tensorclass.py, test/test_tensorclass.py, test/test_tensordict.py
=> [Feature] super() calls within TensorClass subclasses

tensordict/nn/distributions/discrete.py
Fix typo in the definition of `OneHotCategorical`.
`deterministic` is spelled wrong.
close #1129
=> [BugFix] Fix typo in `OneHotCategorical`

tensordict/utils.py
=> [BugFix] Better comparison of tensorclasses

tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/nn/common.py, tensordict/nn/utils.py, tensordict/tensorclass.py
=> [Refactor] Better compile checks

tensordict/nn/probabilistic.py, tensordict/nn/sequence.py, test/test_nn.py
* #1144
* #1143
* __->__ #1142
=> [Feature] OrderedDict for TensorDictSequential

tensordict/nn/common.py, test/test_nn.py
* #1144
* __->__ #1143
* #1142
=> [Feature] Fix type assertion in Seq build

tensordict/nn/common.py
=> [Feature] Optional in_keys for WrapModule

tensordict/nn/probabilistic.py, test/test_nn.py
=> [Feature] Force log_prob to return a tensordict when kwargs are passed to ProbabilisticTensorDictSequential.log_prob

tensordict/base.py, test/test_tensordict.py
=> [BugFix] Fix update_ KeyError when a key from source is missing in dest

tensordict/tensorclass.py, test/test_tensorclass.py
=> [Feature] TensorClass shadow attributes

tensordict/tensorclass.py, test/test_tensordict.py
=> [Feature] NonTensorData(*sequence_of_any)

tensordict/utils.py
=> [BugFix] Use correct default cuda device

tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
* #1166
* #1165
* #1164
* #1163
* __->__ #1162
=> [Feature] TensorDict.logsumexp

tensordict/base.py, tensordict/tensorclass.py, test/test_tensordict.py
* #1166
* #1165
* #1164
* __->__ #1163
* #1162
=> [Feature] TensorDict.softmax

tensordict/tensorclass.py, test/test_tensorclass.py
* #1166
* #1165
* __->__ #1164
* #1163
* #1162
=> [BugFix] Fix unitary ops for tensorclass

docs/source/reference/tensordict.rst, tensordict/_td.py, tensordict/base.py, test/test_tensordict.py
=> [Feature] broadcast pointwise ops for tensor/tensordict mixed inputs

tensordict/functional.py, test/test_tensordict.py
=> [BugFix] Consistent behavior for pad_sequence with one and many non-tensors

tensordict/nn/probabilistic.py
* __->__ #1155
* #1154
* #1153
=> [BugFix] Better return_log_prob=True for tensordict outputs

docs/source/overview.rst
=> [Doc] Better doc for non-tensor data handling

tensordict/tensorclass.pyi, test/test_tensorclass.py
* #1176
* #1175
* __->__ #1174
=> [BE] TensorClass stub method check

test/test_tensorclass.py
* __->__ #1176
* #1175
* #1174
=> [BE] Check ordering and exclusivity of tensorclass registers

tensordict/_torch_func.py, tensordict/tensorclass.py
=> [Feature] Add missing `__torch_function__`

docs/source/overview.rst, tensordict/__init__.py, tensordict/_torch_func.py, tensordict/_unbatched.py, tensordict/base.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensordict.py
=> [Feature] UnbatchedTensor

tensordict/nn/probabilistic.py, test/test_nn.py
=> [Feature] dist_params_keys and dist_sample_keys

tensordict/base.py, tensordict/return_types.py, test/test_tensordict.py
We want `torch.min(tensor, dim=dim)` and `torch.min(tensordict, dim=dim)` to be interchangeable.
Currently, `values` is named vals not to conflict with the method with the same name, and indexing works as it does with tensordict.
This means that a piece of code where we do `torch.min(smth, ...)[idx]` will actually index the resulting tensordict, which is susprising.
I therefore suggest we should just use `torch.reduce_types.<type>` instead.
=> [BugFix] Make min/max tensorclasses be interchangeable with PT equivalent

tensordict/nn/distributions/continuous.py, tensordict/nn/distributions/discrete.py, tensordict/nn/distributions/truncated_normal.py, tensordict/nn/probabilistic.py, test/test_nn.py
=> [Feature] Ensure all dists work with DETERMINSTIC type without warning

docs/source/reference/nn.rst, tensordict/_td.py, tensordict/nn/__init__.py, tensordict/nn/distributions/composite.py, tensordict/nn/probabilistic.py, tensordict/nn/utils.py, test/test_compile.py, test/test_nn.py
I propose a global flag `composite_lp_aggregate` to handle the issue of the aggregation of log-probs.
So far, we have dealt with this using kwargs everywhere (in `ProbabilisticTDModule`, `ProbabilisticTDSequential`, `CompositeDistribution` and subclasses). The hierarchy of these classes and what to do when args conflict isn't easy to handle. It's also confusing for users, who I suspect will usually want to work with either collapsed or non-collapsed log-probs.
A global flag (set to True for now and False in the future) will make things easier to handle. 
Globally, the v0.6.2 behaviour will not be changed all users who rely on it will be informed about the upcoming change through a warning that will tell them to set the global var to `False` to accommodate upcoming changes. If they set it …
=> [Refactor] `composite_lp_aggregate` to handle log-probs aggregates globally

tensordict/functional.py, test/test_tensordict.py
=> [BugFix] Proper masks for padding with custom pad value

tensordict/_td.py, tensordict/_torch_func.py, tensordict/base.py, tensordict/nn/params.py, test/test_tensordict.py
=> [Feature] Subclass conservation in td ops

tensordict/base.py, tensordict/utils.py
=> [BugFix] Fix mem leak when locking

tensordict/_contextlib.py, tensordict/nn/probabilistic.py, test/test_nn.py
=> [Feature] flexible return type when indexing prob sequences

tensordict/nn/utils.py
=> [Feature] COMPOSITE_LP_AGGREGATE env variable

tensordict/tensorclass.py
=> [BugFix] densify non tensor stack is a no-op

tensordict/nn/probabilistic.py
=> [BE] Better warning for composite_lp_aggregate value

docs/source/reference/nn.rst
=> [Doc] Add missing classes to doc

tensordict/nn/utils.py
=> [Feature] Add expln map to NormalParamExtractor

.github/scripts/linux-post-script.sh, .github/workflows/build-wheels-linux.yml, tensordict/nn/distributions/composite.py
=> [CI] Fix GLIBCXX_3.4.29 error

tensordict/nn/distributions/composite.py, tensordict/nn/probabilistic.py, test/test_nn.py
=> [BE] No warning if user sets the log_prob_key explicitly and only one variable is sampled from the ProbTDMod

tensordict/nn/distributions/continuous.py
The doc for `AddStateIndependentNormalScale` indicates of `biased_softplus_1` as the default for the `scale_mapping`, while it is `exp`.
=> [Doc,BugFix] Fix default argument in doc for `AddStateIndependentNormalScale`

docs/source/reference/tensordict.rst, tensordict/__init__.py, tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py
=> [Minor] Expose is_leaf_nontensor and default_is_leaf

tensordict/_lazy.py, tensordict/base.py
* #1222
* #1221
* __->__ #1220
=> [Feature] Allow update to increment the number of tds in a lazy stack

docs/source/reference/tensordict.rst, tensordict/__init__.py, tensordict/base.py, tensordict/tensorclass.py, tensordict/utils.py, test/test_tensorclass.py, test/test_tensordict.py
* #1222
* __->__ #1221
* #1220
=> [Feature] capture_non_tensor_stack

tensordict/base.py, test/test_tensordict.py
=> [BugFix] Consolidate lazy stacks of non-tensors [EDIT]

tensordict/_lazy.py, tensordict/_reductions.py, tensordict/_td.py, tensordict/base.py
=> [BugFix] Pass type directly during reduction

tensordict/nn/common.py
* #1228
* #1227
* __->__ #1226
=> [Doc] Better doc for TensorDictModuleBase

tensordict/nn/common.py, test/test_nn.py
* __->__ #1228
* #1227
* #1226
=> [Feature] TensorDictModule method and kwargs specification

tensordict/_torch_func.py, tensordict/utils.py, test/test_tensorclass.py
=> [BugFix] Fix non-deterministic key order in stack

tensordict/utils.py
=> [BugFix] _PASSTHROUGH_MEMO for passthrough tensorclass

tensordict/nn/common.py, test/test_nn.py
=> [Feature] `strict` kwarg in TDModule

tensordict/_lazy.py, tensordict/_reductions.py, tensordict/base.py, test/test_tensorclass.py
* #1239
* #1237
* __->__ #1236
=> [BugFix] Fix serialization of stacks of Tensorclasses

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/nn/params.py, tensordict/tensorclass.py, tensordict/tensorclass.pyi, tensordict/utils.py, test/test_tensordict.py
* #1239
* __->__ #1237
* #1236
=> [Feature] Update batch-size

tensordict/utils.py
* __->__ #1239
* #1237
* #1236
=> [BugFix] Fix compile during _check_keys

setup.py
Sometimes it's needed to install tensordict with a PyTorch version than are poorly parsed by python's dependency resolver. For instance, Nvidia's [NVCR containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags) come with PyTorch versions that don't follow semver guidelines (are missing a dash after patch). This leads to pip install a version of PyTorch from PyPI. It wold be helpful to be able to specify the needed version inside an environment variable.
`close #1244`
=> [Setup] Parametrize PyTorch version with env variable for local builds

tensordict/nn/common.py
=> [BugFix] Better check for TDModule

tensordict/nn/common.py, test/test_nn.py
=> [BugFix] Fix tensordict.get in TDModule tensor retrieval for NonTensorData

tensordict/base.py, tensordict/tensorclass.py, test/test_tensorclass.py
=> [Feature] from_dataclass with dest_cls arg

docs/source/reference/nn.rst, tensordict/__init__.py, tensordict/nn/__init__.py, tensordict/nn/common.py, test/test_nn.py
=> [Feature] as_tensordict_module

tensordict/_torch_func.py, test/test_tensorclass.py
=> [BugFix] Ensure that maybe_dense_stack preserves the TC type

tensordict/functional.py
The output dimensions of the following docstring example are incorrect:
```
list_td = [
TensorDict({"a": torch.zeros((3, 8)), "b": torch.zeros((6, 8))}, batch_size=[]),
TensorDict({"a": torch.zeros((5, 8)), "b": torch.zeros((6, 8))}, batch_size=[]),
]
```
I ran the above line to verify, and updated the example accordingly.
=> [Doc] Fix typo in pad_sequence docstring example

docs/source/reference/tensordict.rst, tensordict/__init__.py, tensordict/_lazy.py, tensordict/base.py, tensordict/nn/probabilistic.py, tensordict/utils.py, test/test_nn.py, test/test_tensordict.py
=> [Refactor] Setting lists in tensordict instances

tensordict/utils.py
The method `_is_list_tensor_compatible` seems to be missing a return value in one of the return statements.
The function is supposed to return a tuple with three elements `(bool, tuple|None, type|None)`, but one return statement only returns two values.
=> [BugFix] Method _is_list_tensor_compatible missing return value

tensordict/nn/probabilistic.py, test/test_nn.py
* #1294
* #1293
* __->__ #1292
=> [BugFix] num_samples=None fix

tensordict/_td.py, tensordict/base.py, tensordict/persistent.py, tensordict/tensorclass.py
* #1294
* __->__ #1293
* #1292
=> [Deprecation] Enact deprecations

.github/workflows/docs.yml, tutorials/sphinx_tuto/export.py
=> [CI] Fix docs

.github/scripts/version_script.sh, .github/scripts/win-pre-script.bat, tensordict/csrc/CMakeLists.txt, test/smoke_test.py
=> [Setup] statically link _C extension against the Python library

tensordict/nn/sequence.py
Remove an unnecessary try-except in the forward pass of `tensordict.nn.sequential`.
As raised in close #1327, there is an unnecessary try-except in the [forward call](https://github.com/pytorch/tensordict/blob/b5568a99e7bc0d5b3e50d941d71a1a5af007024b/tensordict/nn/sequence.py#L627) of tensordict.nn.sequential:
```
for module in self._module_iter():
try:
tensordict_exec = self._run_module(
module, tensordict_exec, **kwargs
)
except Exception as e:
module_num_or_key = self._get_module_num_or_key(module)
raise RuntimeError(
f"Failed while executing module '{module_num_or_key}'. Scroll up for more info."
) from e
```
This can be frustrating when trying to use PDB to debug, because you would prefer to be dropped into the location of the initial exception so you can inspect variables. There …
=> [Quality] Simplify error handling in TensorDictSequential execution

tensordict/_torch_func.py, test/test_tensordict.py
Adds `torch.maximum` to torch func.
=> [Feature] Adds `torch.maximum` to torch func

tensordict/_td.py, tensordict/utils.py, test/test_tensordict.py
Refactored code in TensorDict.split to add the check ```split_size > 0```; otherwise, raise a RuntimeError.
close #1368, fail fast when ```split_size <= 0```.
=> [BugFix] Add check for split_size in TensorDict.split

tensordict/_lazy.py, tensordict/_td.py, tensordict/base.py, tensordict/tensorclass.py, tensordict/tensorclass.pyi, test/test_tensorclass.py, test/test_tensordict.py
Implement tensor_split for tensordict by following https://docs.pytorch.org/docs/stable/generated/torch.tensor_split.html
- The `tensor_split` function makes sure that the output list after split is equal to the number of chunks specified while the `chunk` function does not.
- [ X] New feature (non-breaking change which adds core functionality)
=> [Feature] implement tensor_split

tutorials/sphinx_tuto/export.py
This pull request focuses on fixing typos and improving the clarity of documentation in the `tutorials/sphinx_tuto/export.py` file. 
To improve readability and accuracy, this fixes minor typos and grammar errors.
=> Fix typos in export tutorial

tensordict/nn/common.py
Changed `TensorDictModuleWrapper` forward method to directly called the wrapped `td_module`.
Fixes #1414 
=> [Bugfix] Fix `TensorDictModuleWrapper` forward

tensordict/tensorclass.py, test/test_tensordict.py
This PR implements type-safe `MetaData` classes using parametric type syntax (e.g., `MetaData[str]`, `MetaData[int]`) with runtime type validation and class caching.
- **Parametric MetaData Types**: Enable creation of type-specific metadata using bracket notation:
```python
metadata = MetaData[str]("hello", batch_size=[3])
metadata = MetaData[int]("hello")  # TypeError: Expected data of type int, got str
```
- **Runtime Type Validation**: Automatically validates that the `data` field matches the expected type during object initialization.
- **Class Caching**: Implements efficient caching to ensure `MetaData[int]` always returns the same class instance, enabling proper `isinstance` checks and maintaining class identity.
- **Enhanced `__new__` method**: Added initialization of …
=> [Feature] Typed MetaData
